export const EASY_ACADEMIC_PASSAGES_M2 = [
  {
    title: "Eusocial Organization and Division of Labor in Hymenoptera",
    text: "Eusociality represents one of the most sophisticated forms of social organization in the animal kingdom, characterized by cooperative brood care, overlapping generations within a single colony, and a strict reproductive division of labor. Within Hymenoptera insect societies—such as honeybees (Apis mellifera), ants, and certain wasps—the colony functions effectively as a single superorganism. A solitary fertile queen assumes exclusive responsibility for oviposition, while thousands of sterile female workers execute all non-reproductive tasks essential to collective survival. These tasks encompass hive construction, meticulous microclimate regulation, brood provisioning, and foraging for floral nectar.\n\nThe temporal polyethism exhibited by worker bees dictates that an individual's duties shift systematically as she ages. Young workers perform interior hive maintenance and nurse developing larvae before transitioning to defensive guarding and eventual outdoor foraging in the final stages of their lifespans. This age-correlated behavioral differentiation optimizes energetic efficiency across the hive. Furthermore, communication regarding rich food resources relies on complex behavioral signaling, notably the famous 'waggle dance,' wherein returning foragers encode precise direction and distance parameters relative to the position of the sun.",
    questions: [
      { id: 1, question: "According to the passage, what defines the reproductive division of labor in eusocial Hymenoptera?", options: ["All females share egg-laying duties equally", "A single fertile queen assumes exclusive responsibility for oviposition", "Drones perform brood care while queens forage"], correct: "A single fertile queen assumes exclusive responsibility for oviposition", hint: "Check the first paragraph regarding queen duties." },
      { id: 2, question: "What does the term 'temporal polyethism' refer to in the context of worker bees?", options: ["Seasonal migration patterns driven by temperature fluctuations", "The systematic shift in worker duties as an individual ages", "Genetic differentiation between workers and drones"], correct: "The systematic shift in worker duties as an individual ages", hint: "Examine the beginning of the second paragraph." },
      { id: 3, question: "How do returning foragers communicate the location of rich floral resources to hive mates?", options: ["Through high-frequency acoustic chirps", "Via complex behavioral signaling known as the waggle dance", "By depositing chemical trail markers outside the hive"], correct: "Via complex behavioral signaling known as the waggle dance", hint: "Read the final sentence of the second paragraph." },
      { id: 4, question: "Which of the following is NOT listed as a defining trait of eusociality in the opening sentence?", options: ["Cooperative brood care", "Overlapping generations within a single colony", "Individualistic territorial foraging"], correct: "Individualistic territorial foraging", hint: "Check the three traits listed in the first sentence." },
      { id: 5, question: "What role do young worker bees fulfill before transitioning to outdoor foraging?", options: ["Exclusive oviposition and queen replacement", "Interior hive maintenance and nursing developing larvae", "Defensive scouting across distant territories"], correct: "Interior hive maintenance and nursing developing larvae", hint: "Look at the second paragraph regarding task progression." },
      { id: 6, question: "Why is an insect colony described as a 'superorganism' in the passage?", options: ["Because individual insects exhibit extreme physical size", "Because highly specialized sterile workers and queens operate as a unified biological entity", "Because colonies frequently merge with neighboring insect species"], correct: "Because highly specialized sterile workers and queens operate as a unified biological entity", hint: "Consider the overall theme of cooperative division of labor." },
      { id: 7, question: "What celestial landmark is used as a reference point in the waggle dance communication?", options: ["The moon's phase", "The position of the sun", "The magnetic north pole"], correct: "The position of the sun", hint: "Check the parameters encoded at the end of the text." },
      { id: 8, question: "Which primary biological advantage is achieved through age-correlated behavioral differentiation?", options: ["Maximization of individual lifespan", "Optimization of energetic efficiency across the hive", "Reduction in total hive population"], correct: "Optimization of energetic efficiency across the hive", hint: "Look near the middle of the second paragraph." },
      { id: 9, question: "What is the primary food resource gathered by worker bees during outdoor foraging?", options: ["Tree resin and bark", "Floral nectar", "Underground root fungi"], correct: "Floral nectar", hint: "Check the list of non-reproductive tasks in paragraph one." },
      { id: 10, question: "What biological gender are all non-reproductive worker bees in Hymenoptera colonies?", options: ["Male", "Female", "Hermaphroditic"], correct: "Female", hint: "Re-read the description of sterile workers in paragraph one." }
    ]
  },
  {
    title: "Syllogistic Logic and Epistemic Validity in Classical Philosophy",
    text: "Classical deductive logic, formalized by Aristotle in the Prior Analytics, centers on the structural validity of syllogistic reasoning. A categorical syllogism consists of exactly three propositions: a major premise, a minor premise, and a conclusive inference. The validity of a syllogistic argument depends strictly on its logical form rather than the empirical truth of its constituent assertions. For instance, if all members of set A belong to set B, and item C belongs to set A, C necessarily belongs to set B. Truth concerns empirical reality, whereas validity governs structural coherence.\n\nDuring the High Middle Ages, Scholastic philosophers integrated Aristotelian logic into formal academic disputation (disputatio) across European universities. Scholars prioritized formal rigor to eliminate informal fallacies such as equivocation, begging the question (petitio principii), and ad hominem evasions. Nevertheless, late Renaissance humanists criticized Scholastic syllogism as sterile and tautological, contending that purely deductive structures could organize existing knowledge but were fundamentally incapable of generating novel empirical discoveries without inductive observation.",
    questions: [
      { id: 1, question: "What fundamental distinction does the passage draw between truth and validity in classical logic?", options: ["Truth governs empirical reality, whereas validity governs structural coherence", "Validity applies only to mathematical proofs, whereas truth applies to rhetoric", "Truth and validity are synonymous terms in Aristotelian philosophy"], correct: "Truth governs empirical reality, whereas validity governs structural coherence", hint: "Examine the conclusion of the first paragraph." },
      { id: 2, question: "How many constituent propositions comprise a formal categorical syllogism?", options: ["Two premises and two conclusions", "Exactly three propositions: major premise, minor premise, and conclusion", "Five independent assertions"], correct: "Exactly three propositions: major premise, minor premise, and conclusion", hint: "Check the second sentence of paragraph one." },
      { id: 3, question: "Why did late Renaissance humanists criticize Scholastic deductive syllogisms?", options: ["Because syllogisms violated Latin grammatical syntax", "Because deduction could organize existing knowledge but could not generate new empirical discoveries", "Because Scholastic scholars rejected Aristotelian texts"], correct: "Because deduction could organize existing knowledge but could not generate new empirical discoveries", hint: "Read the final sentence of paragraph two." },
      { id: 4, question: "Which Aristotelian treatise formalized categorical syllogisms?", options: ["The Nicomachean Ethics", "Prior Analytics", "Poetics"], correct: "Prior Analytics", hint: "Look at the first sentence." },
      { id: 5, question: "What academic exercise in medieval universities heavily utilized Aristotelian logic?", options: ["Disputatio (formal academic disputation)", "Liturgical choral performances", "Alchemical laboratory experiments"], correct: "Disputatio (formal academic disputation)", hint: "Check the second paragraph." },
      { id: 6, question: "Which informal fallacy involves assuming the truth of the conclusion within the premises?", options: ["Ad hominem", "Equivocation", "Begging the question (petitio principii)"], correct: "Begging the question (petitio principii)", hint: "Read the list of fallacies in paragraph two." },
      { id: 7, question: "What determines the structural validity of a categorical syllogism?", options: ["Its alignment with modern scientific observations", "Its structural form regardless of empirical premise truth", "The popularity of the speaker"], correct: "Its structural form regardless of empirical premise truth", hint: "Check sentence three of paragraph one." },
      { id: 8, question: "What alternative method was deemed necessary by humanists to discover novel empirical facts?", options: ["Inductive observation", "Pure deduction", "Mystical contemplation"], correct: "Inductive observation", hint: "Examine the end of paragraph two." },
      { id: 9, question: "Which medieval group systematically integrated Aristotelian logic into university education?", options: ["Scholastic philosophers", "Stoic rhetoricians", "Epicurean poets"], correct: "Scholastic philosophers", hint: "Check sentence one of paragraph two." },
      { id: 10, question: "If an argument is structurally valid but contains false premises, what is its status?", options: ["It is sound and empirically true", "It is valid in form but unsound in fact", "It is completely invalid structurally"], correct: "It is valid in form but unsound in fact", hint: "Synthesize the distinction between form and empirical reality." }
    ]
  }
];

export const NORMAL_ACADEMIC_PASSAGES_M2 = [
  {
    title: "Thermodynamic Entropy, Statistical Mechanics, and the Arrow of Time",
    text: "In classical thermodynamics, the Second Law dictates that the total entropy of an isolated system must non-decrease over time, establishing an irreversible asymmetry known as the thermodynamic arrow of time. Austrian physicist Ludwig Boltzmann revolutionized this concept by reformulating entropy through statistical mechanics. Rather than viewing entropy as a continuous fluid-like quantity, Boltzmann demonstrated that entropy (S) is directly proportional to the natural logarithm of the number of microscopic configurations (W) corresponding to a macrostate, expressed mathematically as S = k ln W.\n\nUnder this statistical paradigm, high-entropy states correspond to macrostates with overwhelmingly greater statistical probability because vastly more microstates yield disordered arrangements than ordered ones. Consequently, systems spontaneously evolve toward thermal equilibrium not due to absolute mechanical constraints, but because microstate phase space makes ordered low-entropy states statistically astronomical anomalies over macroscopic timescales.",
    questions: [
      { id: 1, question: "How did Ludwig Boltzmann transform the understanding of thermodynamic entropy?", options: ["By proving that entropy can decrease in isolated macroscopic systems", "By reformulating entropy as a statistical measure of microscopic configurations", "By disproving the Second Law of Thermodynamics entirely"], correct: "By reformulating entropy as a statistical measure of microscopic configurations", hint: "Examine paragraph one." },
      { id: 2, question: "In Boltzmann's entropy equation S = k ln W, what variable does 'W' represent?", options: ["The total work produced by a heat engine", "The number of microscopic configurations corresponding to a macrostate", "The wave function frequency"], correct: "The number of microscopic configurations corresponding to a macrostate", hint: "Look at the end of paragraph one." },
      { id: 3, question: "Why do isolated systems spontaneously evolve toward high-entropy macrostates?", options: ["Because high-entropy macrostates correspond to overwhelmingly higher statistical microstate probabilities", "Because external gravitational fields force molecules apart", "Because atomic motion completely stops at thermal equilibrium"], correct: "Because high-entropy macrostates correspond to overwhelmingly higher statistical microstate probabilities", hint: "Read paragraph two." },
      { id: 4, question: "What fundamental physics concept establishes irreversible temporal asymmetry?", options: ["The thermodynamic arrow of time", "Quantum entanglement", "Relativistic time dilation"], correct: "The thermodynamic arrow of time", hint: "Check sentence one of paragraph one." },
      { id: 5, question: "What state occurs when a system reaches maximum statistical entropy?", options: ["Superconductivity", "Thermal equilibrium", "Plasma ionization"], correct: "Thermal equilibrium", hint: "Look at sentence two of paragraph two." },
      { id: 6, question: "How are low-entropy macrostates characterized in phase space statistical probabilities?", options: ["As the most common natural states", "As statistically astronomical anomalies", "As perpetually stable configurations"], correct: "As statistically astronomical anomalies", hint: "Read the final line of paragraph two." },
      { id: 7, question: "Which law of physics governs the non-decreasing nature of isolated entropy?", options: ["First Law of Motion", "Second Law of Thermodynamics", "Law of Universal Gravitation"], correct: "Second Law of Thermodynamics", hint: "Check sentence one." },
      { id: 8, question: "What mathematical function links microstates (W) to entropy (S) in Boltzmann's equation?", options: ["Natural logarithm", "Exponential square root", "Linear multiplication"], correct: "Natural logarithm", hint: "Look at S = k ln W." },
      { id: 9, question: "What distinguishes macrostates from microstates in statistical mechanics?", options: ["Macrostates describe macroscopic thermodynamic properties, while microstates detail individual particle arrangements", "Macrostates apply only to liquids, microstates to gases", "There is no functional distinction"], correct: "Macrostates describe macroscopic thermodynamic properties, while microstates detail individual particle arrangements", hint: "Synthesize the contrast between macrostate probability and microstate arrangements." },
      { id: 10, question: "Why is thermal equilibrium statistically irreversible on macroscopic scales?", options: ["Because the probability of spontaneous particle order is practically zero", "Because energy vanishes from the system", "Because chemical bonds break permanently"], correct: "Because the probability of spontaneous particle order is practically zero", hint: "Review the conclusion of paragraph two." }
    ]
  }
];

export const HARD_ACADEMIC_PASSAGES_M2 = [
  {
    title: "Plate Tectonics, Subduction Geodynamics, and Island Arc Volcanism",
    text: "Island arc volcanism is an intrinsic consequence of lithospheric subduction, occurring where an oceanic tectonic plate converges with and plunges beneath another plate into the underlying asthenosphere. As the hydrated oceanic slab descends into regions of elevated temperature and lithostatic pressure, dehydration metamorphic reactions release volatile fluid compounds—principally water and carbon dioxide—into the overriding mantle wedge. These volatiles lower the solidus temperature of mantle peridotite, inducing partial melting through flux melting mechanisms.\n\nThe resulting calc-alkaline magma, enriched in silica, water, and incompatible trace elements, ascends buoyant through the overriding crust to erupt as explosive stratovolcanoes. Over geological epochs, persistent volcanic activity builds arcuate chains of volcanic islands, such as the Aleutian Arc and the Japanese Archipelago. Seismic tomographic profiling reveals that deep subduction zones generate intermediate and deep-focus earthquakes along the dipping Benioff zone, defining the spatial trajectory of descending lithosphere down to depths exceeding 600 kilometers.",
    questions: [
      { id: 1, question: "What triggers partial melting in the overriding mantle wedge during subduction?", options: ["Frictional heat alone melting surrounding granitic rock", "Dehydration metamorphic fluids lowering the solidus temperature of mantle peridotite", "Direct mantle plume updrafts from the core-mantle boundary"], correct: "Dehydration metamorphic fluids lowering the solidus temperature of mantle peridotite", hint: "Read the flux melting description in paragraph one." },
      { id: 2, question: "Which primary volatile compounds are released by descending hydrated oceanic slabs?", options: ["Methane and sulfur dioxide", "Water and carbon dioxide", "Nitrogen gas and argon"], correct: "Water and carbon dioxide", hint: "Check sentence two of paragraph one." },
      { id: 3, question: "What seismic feature delineates the dipping trajectory of subducting lithosphere into the asthenosphere?", options: ["The Wadati-Benioff zone", "The Mid-Atlantic Ridge fault line", "The Moho discontinuity"], correct: "The Wadati-Benioff zone", hint: "Examine the final sentence of paragraph two." },
      { id: 4, question: "What type of magma characteristically forms island arc stratovolcanoes?", options: ["Basaltic tholeiitic magma", "Silica-enriched calc-alkaline magma", "Carbonatite mantle magma"], correct: "Silica-enriched calc-alkaline magma", hint: "Check sentence one of paragraph two." },
      { id: 5, question: "Which island chain is explicitly cited as an example of island arc volcanism?", options: ["The Hawaiian Archipelago", "The Aleutian Arc", "The Iceland rift zone"], correct: "The Aleutian Arc", hint: "Look near the middle of paragraph two." },
      { id: 6, question: "What geologic process describes the descent of one tectonic plate beneath another?", options: ["Subduction", "Seafloor spreading", "Orogenic uplift"], correct: "Subduction", hint: "Read the opening sentence." },
      { id: 7, question: "What impact do volatiles have on the solidus temperature of mantle peridotite?", options: ["They raise the solidus temperature", "They lower the solidus temperature", "They have no effect"], correct: "They lower the solidus temperature", hint: "Check sentence three of paragraph one." },
      { id: 8, question: "Why does calc-alkaline magma ascend through the overriding crustal plate?", options: ["Because it is denser than surrounding continental crust", "Because it is buoyantly less dense than surrounding rock", "Because magnetic field lines pull it upward"], correct: "Because it is buoyantly less dense than surrounding rock", hint: "Look at sentence one of paragraph two." },
      { id: 9, question: "At what maximum depth range can earthquakes occur along the Benioff zone according to the text?", options: ["Less than 50 kilometers", "Depths exceeding 600 kilometers", "Exactly 1,000 kilometers"], correct: "Depths exceeding 600 kilometers", hint: "Check the final clause of the text." },
      { id: 10, question: "What metamorphic process releases fluids from the descending slab?", options: ["Dehydration metamorphism", "Contact thermal baking", "Hydrothermal boiling"], correct: "Dehydration metamorphism", hint: "Examine sentence two of paragraph one." }
    ]
  }
];

export const ADVANCED_ACADEMIC_PASSAGES_M2 = [
  {
    title: "Quantum Electrodynamics, Renormalization Group, and Gauge Invariance",
    text: "Quantum Electrodynamics (QED), the relativistic quantum field theory describing electromagnetic interactions, represents one of the most rigorously verified frameworks in theoretical physics. In QED, charged particles interact through the exchange of virtual gauge bosons (photons). However, early formulations were plagued by ultraviolet divergences—mathematical infinities arising from high-momentum loop integrals in Feynman diagrams. These infinities threatened the physical predictive capacity of the theory until the development of systematic renormalization procedures by Feynman, Schwinger, and Tomonaga.\n\nRenormalization systematically absorbs divergent loop integrals into redefined 'bare' parameters—such as electron charge and mass—yielding finite, physically measurable quantities. Central to this formalism is gauge invariance, dictated by the U(1) local symmetry group, which guarantees charge conservation and enforces the zero rest-mass of the photon. The running coupling constant (alpha) varies logarithmically with energy scale, exhibiting vacuum polarization where virtual electron-positron pairs screen electric charge at long distances, causing the effective electromagnetic interaction strength to increase at subatomic distance scales.",
    questions: [
      { id: 1, question: "What mathematical obstruction initially compromised the predictive capacity of Quantum Electrodynamics?", options: ["Infrared thermal dissipation errors", "Ultraviolet divergences arising from high-momentum loop integrals", "Non-deterministic wave collapse anomalies"], correct: "Ultraviolet divergences arising from high-momentum loop integrals", hint: "Examine paragraph one." },
      { id: 2, question: "How does the mathematical process of renormalization resolve physical parameters in QED?", options: ["By discarding divergent integrals without proof", "By absorbing divergent integrals into bare parameters to yield finite physical values", "By replacing relativistic fields with classical gravity"], correct: "By absorbing divergent integrals into bare parameters to yield finite physical values", hint: "Read paragraph two." },
      { id: 3, question: "Which local symmetry group dictates gauge invariance and charge conservation in QED?", options: ["SU(2) weak symmetry", "U(1) gauge symmetry", "SU(3) color symmetry"], correct: "U(1) gauge symmetry", hint: "Look at paragraph two." },
      { id: 4, question: "What quantum phenomenon causes the fine-structure coupling constant to increase at short distance scales?", options: ["Vacuum polarization screening electric charge", "Higgs boson condensate decay", "Gravitational wave amplification"], correct: "Vacuum polarization screening electric charge", hint: "Read the final sentence of paragraph two." },
      { id: 5, question: "Which virtual particle mediates electromagnetic forces between charged particles in QED?", options: ["Virtual gauge bosons (photons)", "Gluons", "W and Z bosons"], correct: "Virtual gauge bosons (photons)", hint: "Check sentence two of paragraph one." },
      { id: 6, question: "Who among the following was NOT listed among the developers of QED renormalization?", options: ["Richard Feynman", "Julian Schwinger", "Albert Einstein"], correct: "Albert Einstein", hint: "Check the names listed at the end of paragraph one." },
      { id: 7, question: "What fundamental property of the photon is preserved by U(1) gauge invariance?", options: ["Zero rest-mass", "Infinite electric charge", "Sub-luminal speed"], correct: "Zero rest-mass", hint: "Look at paragraph two." },
      { id: 8, question: "What diagrammatic tool represents particle interaction loop integrals in QED?", options: ["Feynman diagrams", "Venn diagrams", "Mendelian grids"], correct: "Feynman diagrams", hint: "Check paragraph one." },
      { id: 9, question: "How does the fine-structure coupling constant behave across varying energy scales?", options: ["It remains completely static regardless of energy", "It varies logarithmically with energy scale", "It drops to zero instantly"], correct: "It varies logarithmically with energy scale", hint: "Examine sentence three of paragraph two." },
      { id: 10, question: "What virtual pairs form the quantum vacuum polarization shield around a charged particle?", options: ["Virtual electron-positron pairs", "Virtual proton-antiproton pairs", "Virtual quark-gluon pairs"], correct: "Virtual electron-positron pairs", hint: "Check the final sentence of the text." }
    ]
  }
];
