export const COMPLETE_WORDS_EASY_M2: any[] = [
  // Exercise 1
  [
    { type: 'text', content: "The natural " },
    { type: 'input', id: 0, prefix: 'en', full: 'environment', missing: 'vironment', hint: 'The surroundings or conditions in which a person, animal, or plant lives.' },
    { type: 'text', content: " is extremely " },
    { type: 'input', id: 1, prefix: 'im', full: 'important', missing: 'portant', hint: 'Of great significance or value.' },
    { type: 'text', content: " for the survival of all living beings. We must work together to " },
    { type: 'input', id: 2, prefix: 'pr', full: 'protect', missing: 'otect', hint: 'Keep safe from harm or injury.' },
    { type: 'text', content: " it from harmful " },
    { type: 'input', id: 3, prefix: 'po', full: 'pollution', missing: 'llution', hint: 'Presence of harmful substances in the environment.' },
    { type: 'text', content: ". Clean air and fresh water are " },
    { type: 'input', id: 4, prefix: 'ne', full: 'necessary', missing: 'cessary', hint: 'Required to be done, achieved, or present.' },
    { type: 'text', content: " for maintaining good " },
    { type: 'input', id: 5, prefix: 'he', full: 'health', missing: 'alth', hint: 'State of physical and mental well-being.' },
    { type: 'text', content: ". Plants need " },
    { type: 'input', id: 6, prefix: 'co', full: 'consistent', missing: 'nsistent', hint: 'Unchanging in achievement or effect over time.' },
    { type: 'text', content: " " },
    { type: 'input', id: 7, prefix: 'su', full: 'sunlight', missing: 'nlight', hint: 'Light from the sun.' },
    { type: 'text', content: " to grow properly. Animals also heavily " },
    { type: 'input', id: 8, prefix: 'de', full: 'depend', missing: 'pend', hint: 'Rely on for support or survival.' },
    { type: 'text', content: " on nature for their " },
    { type: 'input', id: 9, prefix: 'ha', full: 'habitats', missing: 'bitats', hint: 'The natural homes or environments of an animal or plant.' },
    { type: 'text', content: ". Everyone should help " },
    { type: 'input', id: 10, prefix: 'pr', full: 'preserve', missing: 'eserve', hint: 'Maintain something in its original or existing state.' },
    { type: 'text', content: " the planet." }
  ],
  // Exercise 2
  [
    { type: 'text', content: "Solar energy technology captures " },
    { type: 'input', id: 0, prefix: 'ra', full: 'radiant', missing: 'diant', hint: 'Emitted by radiation; bright and shining.' },
    { type: 'text', content: " sunlight using " },
    { type: 'input', id: 1, prefix: 'ph', full: 'photovoltaic', missing: 'otovoltaic', hint: 'Relating to the production of electric current from light.' },
    { type: 'text', content: " panels. These specialized devices convert light directly into clean " },
    { type: 'input', id: 2, prefix: 'el', full: 'electrical', missing: 'ectrical', hint: 'Concerned with or operating by electricity.' },
    { type: 'text', content: " power without " },
    { type: 'input', id: 3, prefix: 'em', full: 'emitting', missing: 'itting', hint: 'Producing and discharging something, especially gas.' },
    { type: 'text', content: " harmful " },
    { type: 'input', id: 4, prefix: 'gr', full: 'greenhouse', missing: 'eenhouse', hint: 'Gases that trap heat in the atmosphere.' },
    { type: 'text', content: " gases. " },
    { type: 'input', id: 5, prefix: 'Re', full: 'Renewable', missing: 'newable', hint: 'Energy from a source that is not depleted when used.' },
    { type: 'text', content: " energy reduces our heavy " },
    { type: 'input', id: 6, prefix: 'de', full: 'dependence', missing: 'pendence', hint: 'The state of relying on or being controlled by something.' },
    { type: 'text', content: " on depleting " },
    { type: 'input', id: 7, prefix: 'fo', full: 'fossil', missing: 'ssil', hint: 'A natural fuel such as coal or gas.' },
    { type: 'text', content: " fuels. Modern solar installations are increasingly " },
    { type: 'input', id: 8, prefix: 'ef', full: 'efficient', missing: 'ficient', hint: 'Achieving maximum productivity with minimum wasted effort.' },
    { type: 'text', content: " and cost-effective for " },
    { type: 'input', id: 9, prefix: 're', full: 'residential', missing: 'sidential', hint: 'Designed for people to live in.' },
    { type: 'text', content: " communities. Transitioning to clean power is " },
    { type: 'input', id: 10, prefix: 'es', full: 'essential', missing: 'sential', hint: 'Absolutely necessary; extremely important.' },
    { type: 'text', content: " for global climate " },
    { type: 'input', id: 11, prefix: 'st', full: 'stabilization', hint: 'The process of making something secure or balanced.', missing: 'abilization' },
    { type: 'text', content: "." }
  ],
  // Exercise 3
  [
    { type: 'input', id: 0, prefix: 'Ph', full: 'Photosynthesis', missing: 'otosynthesis', hint: 'Process by which green plants use sunlight to synthesize nutrients.' },
    { type: 'text', content: " is the " },
    { type: 'input', id: 1, prefix: 'fu', full: 'fundamental', missing: 'ndamental', hint: 'Forming a necessary base or core; of central importance.' },
    { type: 'text', content: " biological mechanism by which green " },
    { type: 'input', id: 2, prefix: 've', full: 'vegetation', missing: 'getation', hint: 'Plants considered collectively in a particular area.' },
    { type: 'text', content: " synthesizes organic nutrients. " },
    { type: 'input', id: 3, prefix: 'Ch', full: 'Chlorophyll', missing: 'lorophyll', hint: 'A green pigment in plants responsible for light absorption.' },
    { type: 'text', content: " molecules within plant leaves absorb light from solar radiation. Combined with subterranean water, plants generate glucose and " },
    { type: 'input', id: 4, prefix: 'li', full: 'liberate', missing: 'berate', hint: 'Set free from a state or bond.' },
    { type: 'text', content: " oxygen gas. This oxygen is vital for " },
    { type: 'input', id: 5, prefix: 'ae', full: 'aerobic', missing: 'robic', hint: 'Requiring free oxygen.' },
    { type: 'text', content: " organisms during cellular " },
    { type: 'input', id: 6, prefix: 're', full: 'respiration', missing: 'spiration', hint: 'Cellular process releasing energy from nutrients.' },
    { type: 'text', content: ". Without photosynthesis, " },
    { type: 'input', id: 7, prefix: 'te', full: 'terrestrial', missing: 'rrestrial', hint: 'Relating to the earth or dry land.' },
    { type: 'text', content: " " },
    { type: 'input', id: 8, prefix: 'ec', full: 'ecosystems', missing: 'osystems', hint: 'Biological communities of interacting organisms.' },
    { type: 'text', content: " would collapse due to a total lack of bioenergy." }
  ],
  // Exercise 4
  [
    { type: 'text', content: "Early human " },
    { type: 'input', id: 0, prefix: 'ci', full: 'civilizations', missing: 'vilizations', hint: 'The stage of human social and cultural development.' },
    { type: 'text', content: " developed along major river valleys due to fertile " },
    { type: 'input', id: 1, prefix: 'ag', full: 'agricultural', missing: 'ricultural', hint: 'Relating to farming or soil cultivation.' },
    { type: 'text', content: " soils. Ancient farmers " },
    { type: 'input', id: 2, prefix: 'co', full: 'constructed', missing: 'nstructed', hint: 'Built or erected something large.' },
    { type: 'text', content: " sophisticated " },
    { type: 'input', id: 3, prefix: 'ir', full: 'irrigation', missing: 'rigation', hint: 'The supply of water to land or crops.' },
    { type: 'text', content: " canals to " },
    { type: 'input', id: 4, prefix: 're', full: 'redirect', missing: 'direct', hint: 'Direct to a new or different place.' },
    { type: 'text', content: " water toward arid croplands. " },
    { type: 'input', id: 5, prefix: 'Re', full: 'Reliable', missing: 'liable', hint: 'Consistently good in quality or performance.' },
    { type: 'text', content: " crop harvests allowed human " },
    { type: 'input', id: 6, prefix: 'se', full: 'settlements', missing: 'ttlements', hint: 'Places where people establish a community.' },
    { type: 'text', content: " to transition from nomadic " },
    { type: 'input', id: 7, prefix: 'fo', full: 'foraging', missing: 'raging', hint: 'Searching for wild food resources.' },
    { type: 'text', content: " to permanent urban centers. Specialized trade crafts, written language, and formal " },
    { type: 'input', id: 8, prefix: 'go', full: 'governance', missing: 'vernance', hint: 'The action or manner of governing a state.' },
    { type: 'text', content: " quickly emerged. Agriculture remains the " },
    { type: 'input', id: 9, prefix: 'fo', full: 'foundation', missing: 'undation', hint: 'An underlying basis or principle.' },
    { type: 'text', content: " of organized human societies." }
  ],
  // Exercise 5
  [
    { type: 'input', id: 0, prefix: 'Co', full: 'Cognitive', missing: 'gnitive', hint: 'Relating to mental processes of understanding.' },
    { type: 'text', content: " " },
    { type: 'input', id: 1, prefix: 'ps', full: 'psychology', missing: 'ychology', hint: 'The scientific study of the human mind and its functions.' },
    { type: 'text', content: " investigates the mental " },
    { type: 'input', id: 2, prefix: 'me', full: 'mechanisms', missing: 'chanisms', hint: 'System of parts working together in a process.' },
    { type: 'text', content: " involved in memory " },
    { type: 'input', id: 3, prefix: 'en', full: 'encoding', missing: 'coding', hint: 'Converting information into a stored memory format.' },
    { type: 'text', content: ", storage, and " },
    { type: 'input', id: 4, prefix: 're', full: 'retrieval', missing: 'trieval', hint: 'The process of getting stored information back.' },
    { type: 'text', content: ". Short-term memory holds a limited " },
    { type: 'input', id: 5, prefix: 'ca', full: 'capacity', missing: 'pacity', hint: 'The maximum amount that something can contain.' },
    { type: 'text', content: " of information, whereas long-term memory organizes vast neural networks over a lifetime. " },
    { type: 'input', id: 6, prefix: 'Co', full: 'Consolidating', missing: 'nsolidating', hint: 'Strengthening into a single whole.' },
    { type: 'text', content: " new information requires focused attention and cognitive " },
    { type: 'input', id: 7, prefix: 're', full: 'repetition', missing: 'petition', hint: 'The action of repeating something.' },
    { type: 'text', content: ". Sleep plays an " },
    { type: 'input', id: 8, prefix: 'in', full: 'indispensable', missing: 'dispensable', hint: 'Absolutely necessary; essential.' },
    { type: 'text', content: " role in strengthening memory pathways in the " },
    { type: 'input', id: 9, prefix: 'ce', full: 'cerebral', missing: 'rebral', hint: 'Relating to the brain or intellect.' },
    { type: 'text', content: " cortex." }
  ],
  // Exercise 6
  [
    { type: 'input', id: 0, prefix: 'Oc', full: 'Oceanography', missing: 'eanography', hint: 'Branch of science dealing with the physical and biological properties of the sea.' },
    { type: 'text', content: " reveals that deep ocean trenches represent extreme " },
    { type: 'input', id: 1, prefix: 'aq', full: 'aquatic', missing: 'uatic', hint: 'Relating to water environments.' },
    { type: 'text', content: " environments. Organisms surviving at " },
    { type: 'input', id: 2, prefix: 'be', full: 'benthic', missing: 'nthic', hint: 'Relating to the bottom of a body of water.' },
    { type: 'text', content: " depths face intense " },
    { type: 'input', id: 3, prefix: 'hy', full: 'hydrostatic', missing: 'drostatic', hint: 'Relating to fluid pressure at rest.' },
    { type: 'text', content: " pressure and pitch darkness. " },
    { type: 'input', id: 4, prefix: 'Hy', full: 'Hydrothermal', missing: 'drothermal', hint: 'Relating to heated water in the earth crust.' },
    { type: 'text', content: " vents spew " },
    { type: 'input', id: 5, prefix: 'mi', full: 'mineral', missing: 'neral', hint: 'Solid naturally occurring inorganic substance.' },
    { type: 'text', content: "-rich fluids that nourish specialized " },
    { type: 'input', id: 6, prefix: 'ch', full: 'chemosynthetic', missing: 'emosynthetic', hint: 'Synthesis of organic compounds by bacteria using inorganic chemical energy.' },
    { type: 'text', content: " bacteria. These unique " },
    { type: 'input', id: 7, prefix: 'mi', full: 'micro-organisms', missing: 'cro-organisms', hint: 'Microscopic living organisms like bacteria.' },
    { type: 'text', content: " form the base of " },
    { type: 'input', id: 8, prefix: 'vi', full: 'vibrant', missing: 'brant', hint: 'Full of energy and life.' },
    { type: 'text', content: " deep-sea food webs without solar energy." }
  ],
  // Exercise 7
  [
    { type: 'text', content: "Urban planners design modern public " },
    { type: 'input', id: 0, prefix: 'tr', full: 'transportation', missing: 'ansportation', hint: 'The action of moving people or goods.' },
    { type: 'text', content: " networks to relieve " },
    { type: 'input', id: 1, prefix: 'me', full: 'metropolitan', missing: 'tropolitan', hint: 'Relating to a large city or urban region.' },
    { type: 'text', content: " traffic " },
    { type: 'input', id: 2, prefix: 'co', full: 'congestion', missing: 'ngestion', hint: 'The state of being overcrowded or blocked.' },
    { type: 'text', content: ". High-speed rail lines and electric bus fleets offer efficient transit " },
    { type: 'input', id: 3, prefix: 'al', full: 'alternatives', missing: 'ternatives', hint: 'Options available as another choice.' },
    { type: 'text', content: " to personal motor vehicles. Upgraded urban " },
    { type: 'input', id: 4, prefix: 'in', full: 'infrastructure', missing: 'frastructure', hint: 'Basic physical structures needed for society.' },
    { type: 'text', content: " reduces carbon " },
    { type: 'input', id: 5, prefix: 'em', full: 'emissions', missing: 'issions', hint: 'Production and discharge of something, especially gas.' },
    { type: 'text', content: " and improves overall air quality. " },
    { type: 'input', id: 6, prefix: 'In', full: 'Investing', missing: 'vesting', hint: 'Expending money or effort with expectation of return.' },
    { type: 'text', content: " in " },
    { type: 'input', id: 7, prefix: 'ac', full: 'accessible', missing: 'cessible', hint: 'Able to be reached or used easily.' },
    { type: 'text', content: " transit fosters economic " },
    { type: 'input', id: 8, prefix: 'pr', full: 'productivity', missing: 'oductivity', hint: 'The state or quality of producing efficiently.' },
    { type: 'text', content: " and " },
    { type: 'input', id: 9, prefix: 'eq', full: 'equitable', missing: 'uitable', hint: 'Fair and impartial.' },
    { type: 'text', content: " mobility for all city residents." }
  ],
  // Exercise 8
  [
    { type: 'input', id: 0, prefix: 'Mi', full: 'Microbiology', missing: 'crobiology', hint: 'Scientific branch dealing with microscopic organisms.' },
    { type: 'text', content: " examines " },
    { type: 'input', id: 1, prefix: 'mi', full: 'microscopic', missing: 'croscopic', hint: 'So small as to be visible only with a microscope.' },
    { type: 'text', content: " organisms including bacteria and viruses. While many bacterial strains perform " },
    { type: 'input', id: 2, prefix: 'be', full: 'beneficial', missing: 'neficial', hint: 'Favorable or advantageous.' },
    { type: 'text', content: " " },
    { type: 'input', id: 3, prefix: 'me', full: 'metabolic', missing: 'tabolic', hint: 'Relating to cellular chemical reactions.' },
    { type: 'text', content: " functions in the microbiome, " },
    { type: 'input', id: 4, prefix: 'pa', full: 'pathogenic', missing: 'thogenic', hint: 'Causing or capable of causing disease.' },
    { type: 'text', content: " strains cause " },
    { type: 'input', id: 5, prefix: 'in', full: 'infectious', missing: 'fectious', hint: 'Transmitted through the environment or contact.' },
    { type: 'text', content: " diseases. Overusing antibiotics " },
    { type: 'input', id: 6, prefix: 'ac', full: 'accelerates', missing: 'celerates', hint: 'Increases in rate or speed.' },
    { type: 'text', content: " the " },
    { type: 'input', id: 7, prefix: 'ev', full: 'evolutionary', missing: 'olutionary', hint: 'Relating to gradual development over generations.' },
    { type: 'text', content: " emergence of superbugs. Researchers must develop novel " },
    { type: 'input', id: 8, prefix: 'an', full: 'antimicrobial', missing: 'timicrobial', hint: 'Agent that kills or stops growth of microbes.' },
    { type: 'text', content: " compounds to combat " },
    { type: 'input', id: 9, prefix: 're', full: 'resilient', missing: 'silient', hint: 'Able to withstand or recover quickly from difficult conditions.' },
    { type: 'text', content: " bacterial pathogens." }
  ],
  // Exercise 9
  [
    { type: 'input', id: 0, prefix: 'Vo', full: 'Volcanic', missing: 'lcanic', hint: 'Relating to or produced by a volcano.' },
    { type: 'text', content: " eruptions occur when molten magma rises beneath the " },
    { type: 'input', id: 1, prefix: 'te', full: 'terrestrial', missing: 'rrestrial', hint: 'Relating to the earth or dry land.' },
    { type: 'text', content: " crust due to " },
    { type: 'input', id: 2, prefix: 'te', full: 'tectonic', missing: 'ctonic', hint: 'Relating to the structure of the earth crust.' },
    { type: 'text', content: " pressure. " },
    { type: 'input', id: 3, prefix: 'Ex', full: 'Explosive', missing: 'plosive', hint: 'Likely to burst violently.' },
    { type: 'text', content: " eruptions eject toxic gases, " },
    { type: 'input', id: 4, prefix: 'in', full: 'incandescent', missing: 'candescent', hint: 'Emitting light as a result of high heat.' },
    { type: 'text', content: " ash, and " },
    { type: 'input', id: 5, prefix: 'py', full: 'pyroclastic', missing: 'roclastic', hint: 'Consisting of rock fragments erupted by a volcano.' },
    { type: 'text', content: " flows into the upper " },
    { type: 'input', id: 6, prefix: 'at', full: 'atmosphere', missing: 'mosphere', hint: 'The envelope of gases surrounding the earth.' },
    { type: 'text', content: ". Despite natural " },
    { type: 'input', id: 7, prefix: 'ha', full: 'hazards', missing: 'zards', hint: 'Dangers or risks.' },
    { type: 'text', content: ", volcanic regions harbor fertile soils and abundant " },
    { type: 'input', id: 8, prefix: 'ge', full: 'geothermal', missing: 'othermal', hint: 'Produced by internal heat of the earth.' },
    { type: 'text', content: " energy. Underground steam spins " },
    { type: 'input', id: 9, prefix: 'tu', full: 'turbines', missing: 'rbines', hint: 'Rotary mechanical devices that extract energy from fluid flow.' },
    { type: 'text', content: " to generate clean power." }
  ],
  // Exercise 10
  [
    { type: 'text', content: "The modern space " },
    { type: 'input', id: 0, prefix: 'ex', full: 'exploration', missing: 'ploration', hint: 'Traveling through an unfamiliar area to learn about it.' },
    { type: 'text', content: " era relies heavily on advanced " },
    { type: 'input', id: 1, prefix: 'ar', full: 'artificial', missing: 'tificial', hint: 'Made or produced by human beings.' },
    { type: 'text', content: " " },
    { type: 'input', id: 2, prefix: 'sa', full: 'satellites', missing: 'tellites', hint: 'Artificial bodies placed in orbit around the earth.' },
    { type: 'text', content: " orbiting Earth. Orbital communication satellites transmit " },
    { type: 'input', id: 3, prefix: 'te', full: 'telecommunication', missing: 'lecommunication', hint: 'Communication over long distance by electronic signals.' },
    { type: 'text', content: " signals and global " },
    { type: 'input', id: 4, prefix: 'na', full: 'navigation', missing: 'vigation', hint: 'Accurately ascertaining position and route.' },
    { type: 'text', content: " data. Space telescopes stationed beyond " },
    { type: 'input', id: 5, prefix: 'at', full: 'atmospheric', missing: 'mospheric', hint: 'Relating to the gases surrounding the earth.' },
    { type: 'text', content: " " },
    { type: 'input', id: 6, prefix: 'tu', full: 'turbulence', missing: 'rbulence', hint: 'Unsteady or violent movement of air.' },
    { type: 'text', content: " capture high-" },
    { type: 'input', id: 7, prefix: 're', full: 'resolution', missing: 'solution', hint: 'The degree of detail visible in an image.' },
    { type: 'text', content: " imagery of distant galaxies and " },
    { type: 'input', id: 8, prefix: 'as', full: 'astronomical', missing: 'tronomical', hint: 'Relating to astronomy or celestial objects.' },
    { type: 'text', content: " phenomena. Robotic probes continue to explore " },
    { type: 'input', id: 9, prefix: 'pl', full: 'planetary', missing: 'anetary', hint: 'Relating to or belonging to a planet.' },
    { type: 'text', content: " surfaces across our solar system." }
  ],
  // Exercise 11
  [
    { type: 'input', id: 0, prefix: 'Nu', full: 'Nutritional', missing: 'tritional', hint: 'Relating to food, diet, and biological nourishment.' },
    { type: 'text', content: " science emphasizes the importance of a balanced diet rich in " },
    { type: 'input', id: 1, prefix: 'es', full: 'essential', missing: 'sential', hint: 'Absolutely necessary.' },
    { type: 'text', content: " " },
    { type: 'input', id: 2, prefix: 'ma', full: 'macronutrients', missing: 'cronutrients', hint: 'Nutritional components required in large amounts.' },
    { type: 'text', content: " and " },
    { type: 'input', id: 3, prefix: 'mi', full: 'micronutrients', missing: 'cronutrients', hint: 'Chemical elements or substances required in trace amounts.' },
    { type: 'text', content: ". Proteins, " },
    { type: 'input', id: 4, prefix: 'ca', full: 'carbohydrates', missing: 'rbohydrates', hint: 'Organic compounds including sugars and starch.' },
    { type: 'text', content: ", and lipids furnish cellular energy for " },
    { type: 'input', id: 5, prefix: 'me', full: 'metabolic', missing: 'tabolic', hint: 'Relating to cellular energy processing.' },
    { type: 'text', content: " processes. Vitamins and minerals act as vital " },
    { type: 'input', id: 6, prefix: 'ca', full: 'catalysts', missing: 'talysts', hint: 'Substances that increase the rate of chemical reactions.' },
    { type: 'text', content: " in " },
    { type: 'input', id: 7, prefix: 'en', full: 'enzymatic', missing: 'zymatic', hint: 'Relating to or produced by enzymes.' },
    { type: 'text', content: " reactions. Balanced nutrition enhances " },
    { type: 'input', id: 8, prefix: 'im', full: 'immune', missing: 'mune', hint: 'Resistant to infection or toxins.' },
    { type: 'text', content: " defense and physical " },
    { type: 'input', id: 9, prefix: 'en', full: 'endurance', missing: 'durance', hint: 'Ability to withstand difficult effort over time.' },
    { type: 'text', content: "." }
  ],
  // Exercise 12
  [
    { type: 'text', content: "Archival " },
    { type: 'input', id: 0, prefix: 'pr', full: 'preservationists', missing: 'eservationists', hint: 'People working toward protecting historic materials.' },
    { type: 'text', content: " utilize chemical techniques to " },
    { type: 'input', id: 1, prefix: 'co', full: 'conserve', missing: 'nserve', hint: 'Protect something from harm or decay.' },
    { type: 'text', content: " rare historic " },
    { type: 'input', id: 2, prefix: 'ma', full: 'manuscripts', missing: 'nuscripts', hint: 'Handwritten books or historical documents.' },
    { type: 'text', content: " and ancient scrolls. Exposure to " },
    { type: 'input', id: 3, prefix: 'ul', full: 'ultraviolet', missing: 'traviolet', hint: 'Radiation with wavelength shorter than visible violet light.' },
    { type: 'text', content: " light and " },
    { type: 'input', id: 4, prefix: 'at', full: 'atmospheric', missing: 'mospheric', hint: 'Relating to gases in the air.' },
    { type: 'text', content: " pollutants degrades " },
    { type: 'input', id: 5, prefix: 'ce', full: 'cellulose', missing: 'llulose', hint: 'Main constituent of plant cell walls and paper.' },
    { type: 'text', content: " fibers. " },
    { type: 'input', id: 6, prefix: 'Co', full: 'Conservators', missing: 'nservators', hint: 'Professionals responsible for preserving artifacts.' },
    { type: 'text', content: " store delicate documents in climate-controlled chambers with neutral " },
    { type: 'input', id: 7, prefix: 'ac', full: 'acidity', missing: 'idity', hint: 'The level of acid in a substance.' },
    { type: 'text', content: ". Digital scanning creates high-" },
    { type: 'input', id: 8, prefix: 're', full: 'resolution', missing: 'solution', hint: 'Detail and clarity visible in an image.' },
    { type: 'text', content: " backups, enabling scholars to study rare " },
    { type: 'input', id: 9, prefix: 'ar', full: 'artifacts', missing: 'tifacts', hint: 'Objects made by humans of cultural or historical interest.' },
    { type: 'text', content: " safely." }
  ],
  // Exercise 13
  [
    { type: 'input', id: 0, prefix: 'Me', full: 'Meteorological', missing: 'teorological', hint: 'Relating to atmospheric science and weather prediction.' },
    { type: 'text', content: " " },
    { type: 'input', id: 1, prefix: 'fo', full: 'forecasting', missing: 'recasting', hint: 'Predicting or estimating a future event or trend.' },
    { type: 'text', content: " combines radar data, " },
    { type: 'input', id: 2, prefix: 'at', full: 'atmospheric', missing: 'mospheric', hint: 'Relating to the envelope of air surrounding Earth.' },
    { type: 'text', content: " pressure, and supercomputer simulations. " },
    { type: 'input', id: 3, prefix: 'Ba', full: 'Barometric', missing: 'rometric', hint: 'Relating to measurement of air pressure.' },
    { type: 'text', content: " " },
    { type: 'input', id: 4, prefix: 'fl', full: 'fluctuations', missing: 'uctuations', hint: 'Irregular variations in amount or level.' },
    { type: 'text', content: " indicate shifting weather fronts. Doppler radar tracks " },
    { type: 'input', id: 5, prefix: 'pr', full: 'precipitation', missing: 'ecipitation', hint: 'Rain, snow, sleet, or hail.' },
    { type: 'text', content: " " },
    { type: 'input', id: 6, prefix: 'in', full: 'intensity', missing: 'tensity', hint: 'Measurable strength or concentration of a force.' },
    { type: 'text', content: " and wind direction. " },
    { type: 'input', id: 7, prefix: 'Ac', full: 'Accurate', missing: 'curate', hint: 'Correct in all details; exact.' },
    { type: 'text', content: " predictions allow " },
    { type: 'input', id: 8, prefix: 'em', full: 'emergency', missing: 'ergency', hint: 'Serious unexpected situation requiring immediate action.' },
    { type: 'text', content: " personnel to issue early warnings to " },
    { type: 'input', id: 9, prefix: 'vu', full: 'vulnerable', missing: 'lnerable', hint: 'Exposed to possibility of harm or damage.' },
    { type: 'text', content: " communities." }
  ],
  // Exercise 14
  [
    { type: 'text', content: "Robotics and " },
    { type: 'input', id: 0, prefix: 'ar', full: 'artificial', missing: 'tificial', hint: 'Made or produced by human beings.' },
    { type: 'text', content: " " },
    { type: 'input', id: 1, prefix: 'in', full: 'intelligence', missing: 'telligence', hint: 'The ability to acquire and apply knowledge.' },
    { type: 'text', content: " are transforming industrial " },
    { type: 'input', id: 2, prefix: 'ma', full: 'manufacturing', missing: 'nufacturing', hint: 'Large-scale making of articles using machinery.' },
    { type: 'text', content: ". Robotic " },
    { type: 'input', id: 3, prefix: 'ma', full: 'manipulators', missing: 'nipulators', hint: 'Mechanical arms or devices used to handle objects.' },
    { type: 'text', content: " perform precise tasks with high mechanical " },
    { type: 'input', id: 4, prefix: 'ac', full: 'accuracy', missing: 'curacy', hint: 'The quality of being correct or precise.' },
    { type: 'text', content: ". Computer vision " },
    { type: 'input', id: 5, prefix: 'al', full: 'algorithms', missing: 'gorithms', hint: 'Step-by-step rules or calculations followed by computers.' },
    { type: 'text', content: " enable " },
    { type: 'input', id: 6, prefix: 'au', full: 'autonomous', missing: 'tonomous', hint: 'Operating independently without human intervention.' },
    { type: 'text', content: " vehicles to navigate complex " },
    { type: 'input', id: 7, prefix: 'en', full: 'environments', missing: 'vironments', hint: 'The surroundings or conditions in which machines operate.' },
    { type: 'text', content: ". Intelligent " },
    { type: 'input', id: 8, prefix: 'au', full: 'automation', missing: 'tomation', hint: 'Use of automatic equipment in an operation.' },
    { type: 'text', content: " increases output while reducing exposure to " },
    { type: 'input', id: 9, prefix: 'ha', full: 'hazardous', missing: 'zardous', hint: 'Risky or dangerous.' },
    { type: 'text', content: " conditions." }
  ],
  // Exercise 15
  [
    { type: 'text', content: "The " },
    { type: 'input', id: 0, prefix: 'hy', full: 'hydrological', missing: 'drological', hint: 'Relating to water movement and distribution on Earth.' },
    { type: 'text', content: " water cycle " },
    { type: 'input', id: 1, prefix: 'co', full: 'continuously', missing: 'ntinuously', hint: 'Without interruption; constantly.' },
    { type: 'text', content: " circulates " },
    { type: 'input', id: 2, prefix: 'te', full: 'terrestrial', missing: 'rrestrial', hint: 'Relating to the earth or land surface.' },
    { type: 'text', content: " moisture through " },
    { type: 'input', id: 3, prefix: 'ev', full: 'evaporation', missing: 'aporation', hint: 'Process of turning liquid into vapor.' },
    { type: 'text', content: ", " },
    { type: 'input', id: 4, prefix: 'co', full: 'condensation', missing: 'ndensation', hint: 'Conversion of vapor or gas into liquid.' },
    { type: 'text', content: ", and " },
    { type: 'input', id: 5, prefix: 'pr', full: 'precipitation', missing: 'ecipitation', hint: 'Rain, snow, or hail falling to earth.' },
    { type: 'text', content: ". Solar heat causes surface water to turn into " },
    { type: 'input', id: 6, prefix: 'at', full: 'atmospheric', missing: 'mospheric', hint: 'Relating to gases in the air.' },
    { type: 'text', content: " vapor. As vapor rises, it " },
    { type: 'input', id: 7, prefix: 'co', full: 'condenses', missing: 'ndenses', hint: 'Changes from gas to liquid drops.' },
    { type: 'text', content: " into clouds. Water eventually replenishes subterranean " },
    { type: 'input', id: 8, prefix: 'aq', full: 'aquifers', missing: 'uifers', hint: 'Permeable rock layers containing groundwater.' },
    { type: 'text', content: " and ocean " },
    { type: 'input', id: 9, prefix: 'ba', full: 'basins', missing: 'sins', hint: 'Large natural depressions containing bodies of water.' },
    { type: 'text', content: "." }
  ],
  // Exercise 16
  [
    { type: 'input', id: 0, prefix: 'Ar', full: 'Architectural', missing: 'chitectural', hint: 'Relating to the design and construction of buildings.' },
    { type: 'text', content: " engineers calculate " },
    { type: 'input', id: 1, prefix: 'st', full: 'structural', missing: 'ructural', hint: 'Relating to the framework of a building.' },
    { type: 'text', content: " loads to withstand " },
    { type: 'input', id: 2, prefix: 'se', full: 'seismic', missing: 'ismic', hint: 'Relating to earthquakes or ground vibrations.' },
    { type: 'text', content: " activity and high winds. " },
    { type: 'input', id: 3, prefix: 'Re', full: 'Reinforced', missing: 'inforced', hint: 'Strengthened with extra structural material.' },
    { type: 'text', content: " concrete pillars distribute heavy " },
    { type: 'input', id: 4, prefix: 'gr', full: 'gravitational', missing: 'avitational', hint: 'Relating to gravity forces.' },
    { type: 'text', content: " weight onto deep " },
    { type: 'input', id: 5, prefix: 'fo', full: 'foundational', missing: 'undational', hint: 'Base or ground layer supporting a building.' },
    { type: 'text', content: " bedrock. Innovative " },
    { type: 'input', id: 6, prefix: 'me', full: 'mechanisms', missing: 'chanisms', hint: 'Systems of working parts.' },
    { type: 'text', content: " absorb " },
    { type: 'input', id: 7, prefix: 'vi', full: 'vibrational', missing: 'brational', hint: 'Relating to rapid back-and-forth movement.' },
    { type: 'text', content: " kinetic energy during shocks. " },
    { type: 'input', id: 8, prefix: 'Su', full: 'Sustainable', missing: 'stainable', hint: 'Eco-friendly and long-lasting.' },
    { type: 'text', content: " design maximizes thermal " },
    { type: 'input', id: 9, prefix: 'in', full: 'insulation', missing: 'sulation', hint: 'Material used to trap heat or prevent heat loss.' },
    { type: 'text', content: "." }
  ],
  // Exercise 17
  [
    { type: 'text', content: "Global " },
    { type: 'input', id: 0, prefix: 'co', full: 'commerce', missing: 'mmerce', hint: 'The activity of buying and selling on a large scale.' },
    { type: 'text', content: " depends on complex supply chain " },
    { type: 'input', id: 1, prefix: 'lo', full: 'logistics', missing: 'gistics', hint: 'Detailed organization and movement of goods.' },
    { type: 'text', content: " and " },
    { type: 'input', id: 2, prefix: 'in', full: 'international', missing: 'ternational', hint: 'Existing or carried on between two or more nations.' },
    { type: 'text', content: " " },
    { type: 'input', id: 3, prefix: 'ma', full: 'maritime', missing: 'ritime', hint: 'Connected with seafaring commercial activity.' },
    { type: 'text', content: " transport networks. Ships carry " },
    { type: 'input', id: 4, prefix: 'ma', full: 'manufactured', missing: 'nufactured', hint: 'Produced on a large scale using machines.' },
    { type: 'text', content: " goods between " },
    { type: 'input', id: 5, prefix: 'co', full: 'commercial', missing: 'mmercial', hint: 'Engaged in trade or business.' },
    { type: 'text', content: " seaports worldwide. Tracking software monitors shipment " },
    { type: 'input', id: 6, prefix: 'in', full: 'inventories', missing: 'ventories', hint: 'Lists or stock of goods in storage.' },
    { type: 'text', content: " and customs " },
    { type: 'input', id: 7, prefix: 'do', full: 'documentation', missing: 'cumentation', hint: 'Official papers providing evidence or record.' },
    { type: 'text', content: " seamlessly. Supply chain " },
    { type: 'input', id: 8, prefix: 'di', full: 'disruptions', missing: 'sruptions', hint: 'Problems that interrupt normal operations.' },
    { type: 'text', content: " can trigger sudden monetary " },
    { type: 'input', id: 9, prefix: 'in', full: 'inflation', missing: 'flation', hint: 'General increase in market prices.' },
    { type: 'text', content: "." }
  ],
  // Exercise 18
  [
    { type: 'text', content: "Wildlife species undertake seasonal " },
    { type: 'input', id: 0, prefix: 'mi', full: 'migrations', missing: 'grations', hint: 'Seasonal movements from one region to another.' },
    { type: 'text', content: " across continents to locate " },
    { type: 'input', id: 1, prefix: 'op', full: 'optimal', missing: 'timal', hint: 'Best or most favorable.' },
    { type: 'text', content: " breeding territories. Migratory birds navigate using " },
    { type: 'input', id: 2, prefix: 'ge', full: 'geomagnetic', missing: 'omagnetic', hint: 'Relating to Earth magnetic field.' },
    { type: 'text', content: " fields, " },
    { type: 'input', id: 3, prefix: 'st', full: 'stellar', missing: 'ellar', hint: 'Relating to stars.' },
    { type: 'text', content: " constellations, and " },
    { type: 'input', id: 4, prefix: 'to', full: 'topographical', missing: 'pographical', hint: 'Relating to physical land features.' },
    { type: 'text', content: " landmarks. However, expanding " },
    { type: 'input', id: 5, prefix: 'ur', full: 'urbanization', missing: 'banization', hint: 'Process of making an area more urban or city-like.' },
    { type: 'text', content: " causes habitat " },
    { type: 'input', id: 6, prefix: 'fr', full: 'fragmentation', missing: 'agmentation', hint: 'Breaking into smaller, isolated parts.' },
    { type: 'text', content: ", creating hazardous " },
    { type: 'input', id: 7, prefix: 'ob', full: 'obstacles', missing: 'stacles', hint: 'Things that block progress or movement.' },
    { type: 'text', content: " along ancestral flight routes. " },
    { type: 'input', id: 8, prefix: 'Co', full: 'Conservation', missing: 'nservation', hint: 'Preservation and protection of natural habitats.' },
    { type: 'text', content: " projects build wildlife corridors to connect isolated " },
    { type: 'input', id: 9, prefix: 'wi', full: 'wilderness', missing: 'lderness', hint: 'Wild, uncultivated natural region.' },
    { type: 'text', content: " areas." }
  ],
  // Exercise 19
  [
    { type: 'text', content: "DNA stores " },
    { type: 'input', id: 0, prefix: 'ge', full: 'genetic', missing: 'netic', hint: 'Relating to genes or heredity.' },
    { type: 'text', content: " code controlling cellular development and biological " },
    { type: 'input', id: 1, prefix: 'in', full: 'inheritance', missing: 'heritance', hint: 'Passing of genetic traits from parents to offspring.' },
    { type: 'text', content: " in living organisms. Double-stranded DNA unwinds during " },
    { type: 'input', id: 2, prefix: 're', full: 'replication', missing: 'plication', hint: 'The action of copying or reproducing.' },
    { type: 'text', content: ", enabling specialized " },
    { type: 'input', id: 3, prefix: 'en', full: 'enzymes', missing: 'zymes', hint: 'Proteins that act as biological catalysts.' },
    { type: 'text', content: " to construct " },
    { type: 'input', id: 4, prefix: 'co', full: 'complementary', missing: 'mplementary', hint: 'Matching or completing a pair.' },
    { type: 'text', content: " daughter strands. " },
    { type: 'input', id: 5, prefix: 'Mu', full: 'Mutations', missing: 'tations', hint: 'Changes in nucleotide sequence.' },
    { type: 'text', content: " in nucleotide sequences introduce biological " },
    { type: 'input', id: 6, prefix: 'va', full: 'variation', missing: 'riation', hint: 'Change or difference in condition or traits.' },
    { type: 'text', content: " across generations. Analyzing " },
    { type: 'input', id: 7, prefix: 'ge', full: 'genomic', missing: 'nomic', hint: 'Relating to a complete set of DNA.' },
    { type: 'text', content: " sequences allows researchers to diagnose " },
    { type: 'input', id: 8, prefix: 'in', full: 'inherited', missing: 'herited', hint: 'Passed down genetically from ancestors.' },
    { type: 'text', content: " medical disorders." }
  ],
  // Exercise 20
  [
    { type: 'text', content: "Modern " },
    { type: 'input', id: 0, prefix: 'ca', full: 'cartography', missing: 'rtography', hint: 'Science or practice of drawing maps.' },
    { type: 'text', content: " relies on satellite remote sensing and " },
    { type: 'input', id: 1, prefix: 'Ge', full: 'Geographic', missing: 'ographic', hint: 'Relating to physical features of Earth.' },
    { type: 'text', content: " Information Systems to map " },
    { type: 'input', id: 2, prefix: 'te', full: 'terrestrial', missing: 'rrestrial', hint: 'Relating to the earth surface.' },
    { type: 'text', content: " landforms. Orbital sensors collect " },
    { type: 'input', id: 3, prefix: 'mu', full: 'multispectral', missing: 'ltispectral', hint: 'Capturing data across multiple light wavelengths.' },
    { type: 'text', content: " imagery of Earth " },
    { type: 'input', id: 4, prefix: 'to', full: 'topography', missing: 'pography', hint: 'Arrangement of physical land features.' },
    { type: 'text', content: ". " },
    { type: 'input', id: 5, prefix: 'Ge', full: 'Geographers', missing: 'ographers', hint: 'Scientists who study Earth landforms and atmosphere.' },
    { type: 'text', content: " analyze " },
    { type: 'input', id: 6, prefix: 'sp', full: 'spatial', missing: 'atial', hint: 'Relating to position or space.' },
    { type: 'text', content: " data to track urban growth and " },
    { type: 'input', id: 7, prefix: 'de', full: 'deforestation', missing: 'forestation', hint: 'Action of clearing forests.' },
    { type: 'text', content: ". Mapping " },
    { type: 'input', id: 8, prefix: 'ap', full: 'applications', missing: 'plications', hint: 'Software programs designed for a specific purpose.' },
    { type: 'text', content: " supply " },
    { type: 'input', id: 9, prefix: 'na', full: 'navigation', missing: 'vigation', hint: 'Determining location and routes accurately.' },
    { type: 'text', content: " tools globally." }
  ]
];
