export const EASY_ACADEMIC_PASSAGES_M1 = [
  {
    title: "The Water Cycle",
    text: "The water cycle, or hydrologic cycle, is the continuous process of water moving around Earth and its atmosphere. This cycle is driven by the sun, which warms water in oceans, lakes, and rivers, turning it from liquid into a gas called water vapor. This process of water turning into gas is known as evaporation. As the warm water vapor rises high into the sky, it cools down and turns back into tiny liquid water droplets, forming clouds. This step is called condensation. When the droplets inside the clouds get too heavy, they fall back to Earth's surface as precipitation, which includes rain, snow, sleet, or hail. Some of this water flows over the ground as runoff, entering rivers and streams, while other water seeps deep into the soil to become groundwater. Eventually, this water travels back to the oceans, and the cycle starts all over again. Plants also play a role by releasing water vapor from their leaves into the air through a process called transpiration.",
    questions: [
      { id: 1, question: "What heats water to turn it into vapor?", options: ["The wind", "The sun", "The moon"], correct: "The sun", hint: "Check the second sentence." },
      { id: 2, question: "What is the name of water falling from clouds?", options: ["Rain or snow", "Vapor", "Oxygen"], correct: "Rain or snow", hint: "Look for the sentence about precipitation." },
      { id: 3, question: "What is the scientific name for the water cycle?", options: ["The nitrogen cycle", "The carbon cycle", "The hydrologic cycle"], correct: "The hydrologic cycle", hint: "Read the very first sentence of the text." },
      { id: 4, question: "What is the process of liquid water turning into a gas called?", options: ["Evaporation", "Condensation", "Precipitation"], correct: "Evaporation", hint: "Find the definition in the third sentence." },
      { id: 5, question: "What is the gas form of water called?", options: ["Oxygen", "Water vapor", "Carbon dioxide"], correct: "Water vapor", hint: "Look at the end of the second sentence." },
      { id: 6, question: "What happens to water vapor as it rises high into the sky?", options: ["It gets hotter and disappears", "It cools down and turns back into liquid", "It turns into solid ice immediately"], correct: "It cools down and turns back into liquid", hint: "Check the fourth sentence about rising vapor." },
      { id: 7, question: "What is the process of water vapor turning back into liquid droplets to form clouds called?", options: ["Transpiration", "Evaporation", "Condensation"], correct: "Condensation", hint: "Check the fifth sentence of the text." },
      { id: 8, question: "Which of the following is NOT a form of precipitation mentioned in the text?", options: ["Sleet", "Wind", "Hail"], correct: "Wind", hint: "Look at the examples of precipitation in the sixth sentence." },
      { id: 9, question: "What is water that flows over the ground into rivers and streams called?", options: ["Runoff", "Groundwater", "Vapor"], correct: "Runoff", hint: "Look at the seventh sentence for water flowing on the ground." },
      { id: 10, question: "What is the process called when plants release water vapor from their leaves?", options: ["Condensation", "Transpiration", "Evaporation"], correct: "Transpiration", hint: "Check the final sentence of the text." }
    ]
  },
  {
    title: "Introduction to Astronomy",
    text: "Astronomy is the study of celestial objects and phenomena beyond Earth's atmosphere. One of the most familiar celestial bodies is the Moon, which is Earth's only natural satellite. A satellite is any object that orbits a larger planet or body. The Moon is extremely bright in the night sky, but it does not actually produce its own light; instead, it reflects light from the Sun. As the Moon orbits Earth, completing a full revolution approximately every 27 days, its position relative to the Earth and the Sun changes. This causes different portions of the Moon's near side to be illuminated by sunlight, creating the various lunar phases we observe from Earth, ranging from the dark new moon to the bright full moon. The gravitational pull of the Moon is also responsible for creating ocean tides on Earth. Because the Moon has no atmosphere, there is no wind or weather, meaning footprints left by astronauts remain undisturbed. Additionally, the Moon has much weaker gravity than Earth, which is about one-sixth of Earth's gravity.",
    questions: [
      { id: 1, question: "Where does the Moon's light come from?", options: ["The Moon itself", "The Sun", "Earth"], correct: "The Sun", hint: "Check the fourth sentence." },
      { id: 2, question: "How long does it take for the Moon to orbit Earth?", options: ["27 days", "365 days", "24 hours"], correct: "27 days", hint: "Check the fifth sentence." },
      { id: 3, question: "What is astronomy defined as in the text?", options: ["The study of weather", "The study of deep oceans", "The study of celestial objects and phenomena"], correct: "The study of celestial objects and phenomena", hint: "Check the very first sentence." },
      { id: 4, question: "What is Earth's only natural satellite?", options: ["The Moon", "The Sun", "Mars"], correct: "The Moon", hint: "Look at the second sentence." },
      { id: 5, question: "What is a satellite?", options: ["A burning ball of gas", "Any object that orbits a larger planet or body", "A telescope in space"], correct: "Any object that orbits a larger planet or body", hint: "Check the third sentence of the passage." },
      { id: 6, question: "What creates the different lunar phases we see from Earth?", options: ["Earth's cloud cover", "The Moon's changing distance from Earth", "Changing positions of Earth, Moon, and Sun causing different parts of the Moon to be illuminated"], correct: "Changing positions of Earth, Moon, and Sun causing different parts of the Moon to be illuminated", hint: "Look at the fifth and sixth sentences." },
      { id: 7, question: "What extreme lunar phases are mentioned in the text?", options: ["New moon and full moon", "Solar eclipse and lunar eclipse", "Crescent moon and gibbous moon"], correct: "New moon and full moon", hint: "Read the end of the sixth sentence." },
      { id: 8, question: "What terrestrial phenomenon is caused by the Moon's gravity?", options: ["Earthquakes", "Volcanic eruptions", "Ocean tides"], correct: "Ocean tides", hint: "Check the seventh sentence of the text." },
      { id: 9, question: "Why do astronaut footprints left on the Moon remain undisturbed?", options: ["Because they are protected by guards", "Because the Moon has no atmosphere, meaning no wind or weather", "Because the lunar soil is made of concrete"], correct: "Because the Moon has no atmosphere, meaning no wind or weather", hint: "Look at the eighth sentence of the text." },
      { id: 10, question: "How strong is gravity on the Moon compared to Earth?", options: ["One-sixth of Earth's gravity", "Six times Earth's gravity", "It is exactly the same"], correct: "One-sixth of Earth's gravity", hint: "Check the final sentence of the text." }
    ]
  },
  {
    title: "Plant Cells vs. Animal Cells",
    text: "Cells are the basic structural and functional units of all living organisms. While all cells share common features, there are significant differences between plant and animal cells. Both plant and animal cells are eukaryotic, meaning they contain fundamental parts such as a nucleus, which houses the cell's genetic material, and cytoplasm, the jelly-like fluid that fills the cell. However, plant cells possess unique structures that animal cells lack. First, plant cells have a rigid outer layer called a cell wall made of cellulose, which provides structural support and helps the plant maintain its shape. Second, they contain chloroplasts, which are specialized organelles that capture sunlight. Using a green pigment called chlorophyll, chloroplasts allow plants to perform photosynthesis to manufacture their own food. Animal cells do not have a cell wall or chloroplasts, allowing them to be more flexible in shape. Furthermore, plant cells typically have one large central vacuole that stores water and maintains turgor pressure, whereas animal cells contain several smaller vacuoles.",
    questions: [
      { id: 1, question: "Which structure is unique to plant cells?", options: ["Nucleus", "Cell wall", "Cytoplasm"], correct: "Cell wall", hint: "Check the fifth sentence." },
      { id: 2, question: "What is the function of chloroplasts?", options: ["Provide support", "Make food via photosynthesis", "Store water"], correct: "Make food via photosynthesis", hint: "Check the seventh sentence." },
      { id: 3, question: "What are cells defined as in the text?", options: ["Small pieces of organs", "Basic structural and functional units of all living organisms", "Chemical mixtures"], correct: "Basic structural and functional units of all living organisms", hint: "Read the very first sentence." },
      { id: 4, question: "What does it mean for a cell to be eukaryotic?", options: ["It does not need oxygen", "It has a cell wall", "It contains fundamental parts like a nucleus"], correct: "It contains fundamental parts like a nucleus", hint: "Check the third sentence of the text." },
      { id: 5, question: "Which cellular part houses the cell's genetic material?", options: ["The cell wall", "The nucleus", "The cytoplasm"], correct: "The nucleus", hint: "Look at the parenthetical note in the third sentence." },
      { id: 6, question: "What is cytoplasm described as in the text?", options: ["A protective shell", "A jelly-like fluid that fills the cell", "An energy generator"], correct: "A jelly-like fluid that fills the cell", hint: "Check the third sentence of the passage." },
      { id: 7, question: "What substance is the plant cell wall made of?", options: ["Cellulose", "Protein", "Starch"], correct: "Cellulose", hint: "Check the fifth sentence of the text." },
      { id: 8, question: "What green pigment is used by chloroplasts during photosynthesis?", options: ["Hemoglobin", "Chlorophyll", "Melanin"], correct: "Chlorophyll", hint: "Check the seventh sentence." },
      { id: 9, question: "Why are animal cells more flexible in shape than plant cells?", options: ["They contain more water", "They do not have a cell wall or chloroplasts", "They have larger vacuoles"], correct: "They do not have a cell wall or chloroplasts", hint: "Check the eighth sentence." },
      { id: 10, question: "How do plant and animal cells differ regarding vacuoles?", options: ["Plant cells have one large central vacuole, while animal cells have several smaller ones", "Only animal cells have vacuoles", "Plant cells have no vacuoles"], correct: "Plant cells have one large central vacuole, while animal cells have several smaller ones", hint: "Check the final sentence." }
    ]
  },
  {
    title: "How Volcanoes Form",
    text: "A volcano is a rupture in the crust of a planetary-mass object, such as Earth, that allows hot lava, volcanic ash, and gases to escape from a magma chamber below the surface. Volcanoes form when molten rock, known as magma, rises from deep inside the Earth's mantle to the surface. This upward movement occurs because magma is less dense and lighter than the solid rock surrounding it. As the magma rises, it accumulates in magma chambers beneath the surface. Eventually, the pressure builds up, causing the magma to break through cracks in the Earth's crust. Once magma erupts onto the Earth's surface, its name changes and it is called lava. Over time, as lava flows out and cools down, it solidifies into hard rock. Repeated eruptions build up layers of rock, ash, and cooled lava, eventually forming volcanic mountains. Volcanoes are typically found where tectonic plates are either diverging or converging, though some form over volcanic hotspots like Hawaii.",
    questions: [
      { id: 1, question: "What is molten rock called before it reaches the surface?", options: ["Lava", "Magma", "Crust"], correct: "Magma", hint: "Check the second sentence." },
      { id: 2, question: "Why does magma rise to the surface?", options: ["It is heavier", "It is less dense and lighter than solid rock", "It is pushed by wind"], correct: "It is less dense and lighter than solid rock", hint: "Check the third sentence." },
      { id: 3, question: "What is a volcano defined as in the text?", options: ["A high-altitude glacier", "A rupture in the crust of a planetary-mass object", "An earthquake epicenter"], correct: "A rupture in the crust of a planetary-mass object", hint: "Read the very first sentence." },
      { id: 4, question: "Where does magma originate before rising?", options: ["Deep inside the Earth's mantle", "On top of the crust", "In the ocean floor"], correct: "Deep inside the Earth's mantle", hint: "Check the second sentence." },
      { id: 5, question: "Where does magma accumulate as it rises towards the surface?", options: ["In volcanic craters", "In magma chambers beneath the surface", "In the atmosphere"], correct: "In magma chambers beneath the surface", hint: "Check the fourth sentence." },
      { id: 6, question: "What causes magma to eventually break through the Earth's crust?", options: ["Pressure builds up", "Global temperature decreases", "Wind blowing over the crust"], correct: "Pressure builds up", hint: "Check the fifth sentence." },
      { id: 7, question: "What is molten rock called once it erupts onto the surface?", options: ["Basalt", "Magma", "Lava"], correct: "Lava", hint: "Check the sixth sentence." },
      { id: 8, question: "What happens to lava over time as it flows out?", options: ["It evaporates", "It cools down and solidifies into hard rock", "It becomes softer"], correct: "It cools down and solidifies into hard rock", hint: "Check the seventh sentence." },
      { id: 9, question: "How are volcanic mountains built up over time?", options: ["Repeated eruptions build up layers of rock, ash, and cooled lava", "By wind-swept sand piling up", "By tectonic plates sliding over each other"], correct: "Repeated eruptions build up layers of rock, ash, and cooled lava", hint: "Check the eighth sentence." },
      { id: 10, question: "What is an example of a volcanic hotspot mentioned in the text?", options: ["Rotterdam", "Singapore", "Hawaii"], correct: "Hawaii", hint: "Check the final sentence of the text." }
    ]
  },
  {
    title: "History of Paper Making",
    text: "The history of paper is a fascinating journey of human innovation that revolutionized communication and record-keeping. Paper was officially invented in China around the year 105 AD during the Han Dynasty. The invention is attributed to a court official named Cai Lun, who presented his work to the emperor. Before this invention, people wrote on heavy materials like bamboo tablets, wooden boards, or expensive silk sheets. Cai Lun's early paper-making process involved using readily available raw materials, including plant fibers, mulberry bark, hemp, and old rags. These ingredients were chopped, boiled, and beaten into a pulp, which was then mixed with water. This watery pulp mixture was poured onto a fine screen or mold, allowing the water to drain away. The remaining layer of wet fibers was flattened, pressed to remove excess moisture, and dried in the sun. This process created a thin, flexible, and lightweight writing material. The new invention quickly spread across Asia and eventually reached Europe, laying the foundation for modern printing and education.",
    questions: [
      { id: 1, question: "Where was paper invented?", options: ["Egypt", "China", "Rome"], correct: "China", hint: "Check the second sentence." },
      { id: 2, question: "What material did early paper replace?", options: ["Bamboo tablets", "Clay tablets", "Parchment"], correct: "Bamboo tablets", hint: "Check the fourth sentence." },
      { id: 3, question: "When was paper officially invented according to the text?", options: ["Around 105 AD", "In 1050 BC", "In 1440 AD"], correct: "Around 105 AD", hint: "Check the second sentence." },
      { id: 4, question: "Who is credited with the invention of paper?", options: ["Johannes Gutenberg", "Cai Lun", "Julius Caesar"], correct: "Cai Lun", hint: "Check the third sentence." },
      { id: 5, question: "During which Chinese Dynasty was paper invented?", options: ["Tang Dynasty", "Han Dynasty", "Ming Dynasty"], correct: "Han Dynasty", hint: "Look at the end of the second sentence." },
      { id: 6, question: "Which of the following was NOT used as a raw material for early paper?", options: ["Mulberry bark", "Old rags", "Plaster"], correct: "Plaster", hint: "Look at the list of materials in the fifth sentence." },
      { id: 7, question: "What did the raw materials have to be beaten into during the process?", options: ["A solid sheet", "A watery pulp", "Fine powder"], correct: "A watery pulp", hint: "Check the sixth sentence." },
      { id: 8, question: "What was used to drain the water from the pulp mixture?", options: ["A fine screen or mold", "A porous stone", "A heavy press"], correct: "A fine screen or mold", hint: "Check the seventh sentence." },
      { id: 9, question: "How was the flattened wet fiber layer dried?", options: ["Over a fire", "By baking in an oven", "In the sun"], correct: "In the sun", hint: "Check the eighth sentence." },
      { id: 10, question: "What were the properties of the writing material created by Cai Lun?", options: ["Heavy and rigid", "Thin, flexible, and lightweight", "Brittle and thick"], correct: "Thin, flexible, and lightweight", hint: "Check the ninth sentence of the text." }
    ]
  },
  {
    title: "Ancient Egyptian Pyramids",
    text: "The pyramids of ancient Egypt are among the most impressive architectural feats of the ancient world. Built during the Old and Middle Kingdom periods, these monumental structures served as grand tombs for the pharaohs, who were the kings of Egypt and believed to be divine mediators between gods and humans. The Egyptians believed that a pharaoh's soul, or 'ka,' needed a secure physical resting place to transition successfully into the afterlife. Constructed primarily from massive blocks of limestone and granite, these pyramids were meticulously designed to protect the king's mummified body and his valuable worldly belongings from tomb robbers. The walls of the inner chambers were often decorated with hieroglyphic inscriptions and paintings intended to guide the pharaoh in the next world. The most famous and largest of these structures is the Great Pyramid of Giza, built for the Pharaoh Khufu. It stood as the tallest man-made structure in the world for over 3,800 years, showcasing the advanced engineering, mathematical skills, and organized labor of ancient Egyptian society.",
    questions: [
      { id: 1, question: "Why did Egyptians build pyramids?", options: ["As palaces", "As tombs for pharaohs", "As astronomical observatories"], correct: "As tombs for pharaohs", hint: "Check the second sentence." },
      { id: 2, question: "What material was primarily used to build pyramids?", options: ["Wood", "Limestone and granite blocks", "Bricks"], correct: "Limestone and granite blocks", hint: "Check the fourth sentence." },
      { id: 3, question: "During which historical periods of Egypt were the pyramids constructed?", options: ["Old and Middle Kingdom periods", "New Kingdom period only", "The Ptolemaic period"], correct: "Old and Middle Kingdom periods", hint: "Check the second sentence." },
      { id: 4, question: "Who were the pharaohs believed to be in ancient Egypt?", options: ["Ordinary mortal rulers", "Divine mediators between gods and humans", "Foreign conquerors"], correct: "Divine mediators between gods and humans", hint: "Look at the end of the second sentence." },
      { id: 5, question: "What did the ancient Egyptians call the pharaoh's soul?", options: ["Ka", "Pharaoh", "Khufu"], correct: "Ka", hint: "Check the third sentence." },
      { id: 6, question: "What was the purpose of protecting the pharaoh's soul and body?", options: ["To prevent them from being forgotten", "To ensure a successful transition into the afterlife", "To frighten enemies"], correct: "To ensure a successful transition into the afterlife", hint: "Look at the end of the third sentence." },
      { id: 7, question: "What did the pyramids protect the king's body and belongings from?", options: ["Erosion", "Tomb robbers", "Natural floods"], correct: "Tomb robbers", hint: "Check the fourth sentence." },
      { id: 8, question: "What was placed on the walls of the inner chambers to guide the pharaoh?", options: ["Hieroglyphic inscriptions and paintings", "Maps of the Nile", "Bronze mirrors"], correct: "Hieroglyphic inscriptions and paintings", hint: "Check the fifth sentence." },
      { id: 9, question: "For which specific pharaoh was the Great Pyramid of Giza built?", options: ["Pharaoh Tutankhamun", "Pharaoh Ramesses II", "Pharaoh Khufu"], correct: "Pharaoh Khufu", hint: "Check the sixth sentence." },
      { id: 10, question: "How long did the Great Pyramid of Giza hold the record as the tallest man-made structure?", options: ["Over 3,800 years", "Exactly 1,000 years", "Until the modern era (5,000 years)"], correct: "Over 3,800 years", hint: "Check the final sentence of the passage." }
    ]
  },
  {
    title: "Rainforest Biodiversity",
    text: "Tropical rainforests are some of the most ecologically significant biomes on Earth. Although tropical rainforests cover only about six percent of the Earth's total land surface, they are incredibly dense with life, serving as home to more than half of the world's diverse plant and animal species. This immense biological richness, known as biodiversity, is primarily due to the unique environmental conditions of the tropics. Rainforests enjoy a warm climate year-round with temperatures rarely dropping below 68 degrees Fahrenheit, coupled with abundant annual rainfall that often exceeds 80 inches. These stable, warm, and wet conditions prevent seasonal die-offs and encourage continuous plant growth. The rainforest structure is divided into distinct vertical layers: the forest floor, the understory, the canopy, and the emergent layer. Each of these dense layers of vegetation offers a unique microclimate and habitat, allowing specialized organisms to evolve and thrive. Rainforest plants also act as the 'lungs of the Earth' by absorbing carbon dioxide and producing large amounts of oxygen.",
    questions: [
      { id: 1, question: "How much of Earth's land is covered by tropical rainforests?", options: ["Fifty percent", "Six percent", "Sixteen percent"], correct: "Six percent", hint: "Check the second sentence." },
      { id: 2, question: "What causes the high biodiversity in rainforests?", options: ["Cold weather", "Warm climate, abundant rainfall, and vertical structures", "Lack of plants"], correct: "Warm climate, abundant rainfall, and vertical structures", hint: "Check the third and fourth sentences." },
      { id: 3, question: "What is the biological richness of the rainforest called?", options: ["Ecosystem stability", "Biodiversity", "Biomass"], correct: "Biodiversity", hint: "Check the third sentence." },
      { id: 4, question: "What is the typical minimum year-round temperature in a rainforest?", options: ["32 degrees Fahrenheit", "68 degrees Fahrenheit", "100 degrees Fahrenheit"], correct: "68 degrees Fahrenheit", hint: "Check the fourth sentence." },
      { id: 5, question: "How much annual rainfall does a tropical rainforest typically receive?", options: ["Less than 10 inches", "Around 40 inches", "More than 80 inches"], correct: "More than 80 inches", hint: "Check the fourth sentence." },
      { id: 6, question: "How do stable, warm, and wet conditions affect rainforest life?", options: ["They cause frequent droughts", "They prevent seasonal die-offs and encourage continuous plant growth", "They limit the number of insect species"], correct: "They prevent seasonal die-offs and encourage continuous plant growth", hint: "Check the fifth sentence." },
      { id: 7, question: "Into how many distinct vertical layers is the rainforest structure divided?", options: ["Two layers", "Four layers", "Ten layers"], correct: "Four layers", hint: "Check the sixth sentence." },
      { id: 8, question: "Which of the following is NOT a vertical layer of the rainforest mentioned?", options: ["The canopy", "The emergent layer", "The ocean reef floor"], correct: "The ocean reef floor", hint: "Look at the list of layers in the sixth sentence." },
      { id: 9, question: "Why do specialized organisms thrive in different layers of the rainforest?", options: ["Because each layer offers a unique microclimate and habitat", "Because they can fly easily between layers", "Because they eat the same food"], correct: "Because each layer offers a unique microclimate and habitat", hint: "Check the seventh sentence." },
      { id: 10, question: "Why are rainforest plants referred to as the 'lungs of the Earth'?", options: ["They look like giant lung lobes", "They absorb carbon dioxide and produce large amounts of oxygen", "They are highly fragile"], correct: "They absorb carbon dioxide and produce large amounts of oxygen", hint: "Check the final sentence of the text." }
    ]
  },
  {
    title: "The Great Barrier Reef",
    text: "The Great Barrier Reef is a breathtaking natural wonder located in the Coral Sea, off the northeastern coast of Australia. Spanning over 1,400 miles, it is recognized as the largest coral reef system on the planet. This colossal structure is so immense that it can actually be seen from outer space. Remarkably, the entire reef is built by billions of tiny, soft-bodied organisms called coral polyps. These polyps secrete a hard calcium carbonate skeleton that forms the structural backbone of the reef. As generations of polyps die and new ones grow on top, the reef slowly expands over thousands of years. This vibrant underwater ecosystem acts as a critical marine sanctuary, supporting thousands of species. It is home to colorful tropical fish, majestic sea turtles, various species of sharks, dolphins, and vibrant sea anemones. However, the Great Barrier Reef is currently facing severe threats from human activity and climate change, which cause ocean temperatures to rise and trigger devastating coral bleaching events.",
    questions: [
      { id: 1, question: "Where is the Great Barrier Reef located?", options: ["Off the northeastern coast of Australia", "In the Atlantic Ocean", "Near Florida"], correct: "Off the northeastern coast of Australia", hint: "Check the first sentence." },
      { id: 2, question: "What organisms build the reef system?", options: ["Sea turtles", "Coral polyps", "Algae"], correct: "Coral polyps", hint: "Check the fourth sentence." },
      { id: 3, question: "In which specific sea is the Great Barrier Reef situated?", options: ["The Tasman Sea", "The Coral Sea", "The Mediterranean Sea"], correct: "The Coral Sea", hint: "Check the first sentence." },
      { id: 4, question: "How long is the Great Barrier Reef?", options: ["Over 100 miles", "Over 1,400 miles", "Over 10,000 miles"], correct: "Over 1,400 miles", hint: "Check the second sentence." },
      { id: 5, question: "Can the Great Barrier Reef be seen from outer space?", options: ["Yes, due to its colossal structure", "No, it is too deep underground", "Only with highly specialized microscopes"], correct: "Yes, due to its colossal structure", hint: "Check the third sentence." },
      { id: 6, question: "What chemical substance do coral polyps secrete to build the reef?", options: ["Sodium chloride", "Calcium carbonate", "Silica"], correct: "Calcium carbonate", hint: "Check the fifth sentence." },
      { id: 7, question: "How does the reef expand over thousands of years?", options: ["By sediment washing in from rivers", "By generations of polyps dying and new ones growing on top", "By volcanic eruptions"], correct: "By generations of polyps dying and new ones growing on top", hint: "Check the sixth sentence." },
      { id: 8, question: "Which of the following is NOT listed as a resident of the reef?", options: ["Dolphins", "Sea turtles", "Polar bears"], correct: "Polar bears", hint: "Check the eighth sentence for listed marine life." },
      { id: 9, question: "What are the primary threats facing the Great Barrier Reef today?", options: ["Lack of sunlight and high pressure", "Human activity and climate change", "Overpopulation of sharks"], correct: "Human activity and climate change", hint: "Check the final sentence." },
      { id: 10, question: "What happens to the coral reef when ocean temperatures rise too high?", options: ["It grows much faster", "It turns into sand", "It undergoes devastating coral bleaching events"], correct: "It undergoes devastating coral bleaching events", hint: "Look at the end of the final sentence." }
    ]
  },
  {
    title: "Introduction to Gravity",
    text: "Gravity is a fundamental and invisible force of nature that pulls objects toward each other. It is the force that keeps our feet firmly planted on the ground and prevents the atmosphere from drifting into space. Every object in the universe that has mass exerts a gravitational pull, with larger masses producing stronger gravitational forces. Sir Isaac Newton, a prominent English physicist and mathematician, was the first scientist to mathematically describe this force in the late 17th century. Legend has it that Newton's breakthrough came after he observed an apple falling from a tree in his orchard. This simple event led him to realize that the very same force responsible for pulling the apple down to Earth is also responsible for keeping the Moon in its orbit around the Earth, and the planets in their elliptical orbits around the Sun. Later, in the 20th century, Albert Einstein refined our understanding of gravity with his Theory of General Relativity, showing that gravity is actually the bending of space and time caused by mass.",
    questions: [
      { id: 1, question: "Who first mathematically described gravity?", options: ["Galileo Galilei", "Sir Isaac Newton", "Albert Einstein"], correct: "Sir Isaac Newton", hint: "Check the fourth sentence." },
      { id: 2, question: "What does gravity do?", options: ["Pushes objects away", "Pulls objects toward each other", "Heats objects up"], correct: "Pulls objects toward each other", hint: "Check the first sentence." },
      { id: 3, question: "What key biological/meteorological layer does gravity prevent from escaping into space?", options: ["The oceans", "The atmosphere", "The soil"], correct: "The atmosphere", hint: "Check the second sentence." },
      { id: 4, question: "What physical property must an object have to exert a gravitational pull?", options: ["Mass", "Charge", "Luster"], correct: "Mass", hint: "Check the third sentence." },
      { id: 5, question: "How does the mass of an object affect its gravitational force?", options: ["Larger masses produce stronger gravitational forces", "Larger masses produce weaker forces", "Mass has no effect on gravity"], correct: "Larger masses produce stronger gravitational forces", hint: "Check the third sentence." },
      { id: 6, question: "What country was Sir Isaac Newton from?", options: ["France", "Germany", "England"], correct: "England", hint: "Look at his description as an 'English physicist' in the fourth sentence." },
      { id: 7, question: "What legendary event in Newton's orchard inspired his discovery?", options: ["An apple falling from a tree", "A lightning strike", "A solar eclipse"], correct: "An apple falling from a tree", hint: "Check the fifth sentence." },
      { id: 8, question: "According to Newton, what keeps the Moon in orbit around the Earth?", options: ["Magnetic attraction", "The same gravitational force that pulls an apple to Earth", "Solar winds"], correct: "The same gravitational force that pulls an apple to Earth", hint: "Check the sixth sentence." },
      { id: 9, question: "Who refined our understanding of gravity in the 20th century?", options: ["Johannes Kepler", "Albert Einstein", "Stephen Hawking"], correct: "Albert Einstein", hint: "Check the final sentence." },
      { id: 10, question: "What is Einstein's description of gravity?", options: ["An electromagnetic pull", "The bending of space and time caused by mass", "A molecular bond"], correct: "The bending of space and time caused by mass", hint: "Read the final sentence of the text." }
    ]
  },
  {
    title: "Honeybee Pollination",
    text: "Honeybees are some of the most industrious and essential insects on Earth, playing a vital role in both natural ecosystems and global agriculture. Their most important contribution is pollination, the process required for flowering plants to reproduce. Honeybees visit flowers primarily to collect sweet liquid nectar, which they use as food and to make honey. As a bee crawls inside a flower to reach the nectar, tiny pollen grains from the flower's male reproductive parts, called anthers, stick to the bee's fuzzy, hair-covered body. When the bee flies to another flower of the same species in search of more food, some of that trapped pollen rubs off onto the female reproductive part, called the stigma. This transfer of pollen, known as pollination, fertilizes the plant, enabling it to produce seeds, fruits, and vegetables. Without honeybees, many of the crops we rely on for food, such as apples, almonds, and berries, would fail to produce. However, honeybee populations are currently threatened by pesticide use, habitat loss, and disease.",
    questions: [
      { id: 1, question: "What do bees collect from flowers?", options: ["Pollen grains", "Nectar", "Water"], correct: "Nectar", hint: "Check the third sentence." },
      { id: 2, question: "How does pollination help plants?", options: ["Helps them grow leaves", "Allows them to fertilize and produce seeds, fruits, and vegetables", "Protects them from pests"], correct: "Allows them to fertilize and produce seeds, fruits, and vegetables", hint: "Check the sixth sentence." },
      { id: 3, question: "Why are honeybees described as vital to agriculture?", options: ["They eat harmful insects", "They pollinate flowering plants necessary for food crops", "They produce wax for candles"], correct: "They pollinate flowering plants necessary for food crops", hint: "Check the first and second sentences." },
      { id: 4, question: "What do bees do with the collected nectar?", options: ["They use it as food and to make honey", "They store it in the soil", "They feed it to other insects"], correct: "They use it as food and to make honey", hint: "Check the third sentence." },
      { id: 5, question: "What are the male reproductive parts of a flower called?", options: ["Anthers", "Stigmas", "Petals"], correct: "Anthers", hint: "Check the fourth sentence." },
      { id: 6, question: "How does pollen physically adhere to a honeybee?", options: ["Using a sticky wax they secrete", "It sticks to the bee's fuzzy, hair-covered body", "It gets caught in their wings"], correct: "It sticks to the bee's fuzzy, hair-covered body", hint: "Check the fourth sentence." },
      { id: 7, question: "What is the female reproductive part of a flower called?", options: ["The anther", "The pollen grain", "The stigma"], correct: "The stigma", hint: "Check the fifth sentence." },
      { id: 8, question: "What is the scientific term for transferring pollen from an anther to a stigma?", options: ["Photosynthesis", "Pollination", "Transpiration"], correct: "Pollination", hint: "Check the sixth sentence." },
      { id: 9, question: "Name three food crops mentioned that rely on honeybee pollination.", options: ["Wheat, rice, and corn", "Apples, almonds, and berries", "Potatoes, carrots, and onions"], correct: "Apples, almonds, and berries", hint: "Check the seventh sentence." },
      { id: 10, question: "What is currently threatening honeybee populations?", options: ["Overpopulation of flowers", "Pesticide use, habitat loss, and disease", "Extreme cold weather only"], correct: "Pesticide use, habitat loss, and disease", hint: "Check the final sentence of the text." }
    ]
  },
  {
    title: "Glaciers and Ice Sheets",
    text: "Glaciers are massive, slow-moving bodies of ice that form in high-altitude mountains or polar regions where temperatures remain freezing year-round. They begin to form when more snow falls in the winter than melts during the brief summer months. Over hundreds or even thousands of years, accumulating layers of heavy snow pile on top of each other. The weight of the upper layers compresses the underlying snow, squeezing out air bubbles and turning it into highly dense glacial ice. Due to their immense weight and the force of gravity, glaciers do not remain stationary. Instead, they slowly flow downhill and across landscapes, behaving like extremely slow-moving rivers of ice. As they slide, glaciers carve out dramatic U-shaped valleys and scrape away rocks, reshaping the terrain. Today, glaciers and ice sheets store about 69 percent of the world's freshwater. However, due to global warming, glaciers worldwide are melting at unprecedented rates, contributing to rising sea levels.",
    questions: [
      { id: 1, question: "How do glaciers form?", options: ["From frozen ocean water", "Snow compresses into thick ice over centuries due to accumulating layers", "Rainwater freezing instantly"], correct: "Snow compresses into thick ice over centuries due to accumulating layers", hint: "Check the third and fourth sentences." },
      { id: 2, question: "Why do glaciers flow downhill?", options: ["Due to wind", "Due to their immense weight and gravity", "Because the Earth spins"], correct: "Due to their immense weight and gravity", hint: "Check the fifth sentence." },
      { id: 3, question: "Where are glaciers typically found?", options: ["In tropical deserts", "In high-altitude mountains or polar regions", "Under the ocean floor"], correct: "In high-altitude mountains or polar regions", hint: "Check the first sentence." },
      { id: 4, question: "Under what weather/melt conditions do glaciers start forming?", options: ["When winters are very short", "When more snow falls in winter than melts in summer", "When it rains constantly"], correct: "When more snow falls in winter than melts in summer", hint: "Check the second sentence." },
      { id: 5, question: "What is squeezed out of snow when it compresses into dense glacial ice?", options: ["Water droplets", "Air bubbles", "Dirt"], correct: "Air bubbles", hint: "Check the fourth sentence." },
      { id: 6, question: "What are glaciers compared to because of their slow movement?", options: ["Slow-moving rivers of ice", "Frozen waterfalls", "Stationary icebergs"], correct: "Slow-moving rivers of ice", hint: "Check the sixth sentence." },
      { id: 7, question: "What type of valleys do glaciers carve out as they slide?", options: ["V-shaped valleys", "U-shaped valleys", "Flat plains"], correct: "U-shaped valleys", hint: "Check the seventh sentence." },
      { id: 8, question: "How do glaciers affect the surrounding terrain as they slide?", options: ["They scrape away rocks and reshape the landscape", "They have no effect on the landscape", "They cover it in liquid water immediately"], correct: "They scrape away rocks and reshape the landscape", hint: "Check the seventh sentence." },
      { id: 9, question: "What percentage of the world's freshwater is stored in glaciers and ice sheets?", options: ["10 percent", "69 percent", "99 percent"], correct: "69 percent", hint: "Check the eighth sentence." },
      { id: 10, question: "What global environmental issue is causing glaciers to melt?", options: ["Tornadoes", "Global warming", "Acid rain"], correct: "Global warming", hint: "Check the final sentence." }
    ]
  },
  {
    title: "The Discovery of Penicillin",
    text: "The discovery of penicillin is considered one of the greatest medical breakthroughs in human history, marking the beginning of the age of modern antibiotics. In 1928, Scottish bacteriologist Alexander Fleming returned to his laboratory in London after a two-week vacation. He noticed that one of his petri dishes containing Staphylococcus bacteria had been left uncovered and was contaminated by a green mold. Upon closer inspection under his microscope, Fleming observed that the bacteria immediately surrounding the mold had been destroyed, while bacteria further away remained active. He identified the mold as Penicillium notatum and concluded that it was secreting a substance that actively killed the harmful bacteria. He named this active substance penicillin. Although Fleming struggled to isolate and mass-produce the compound, later work by scientists Howard Florey and Ernst Chain in the 1940s successfully turned penicillin into a life-saving medicine. This drug revolutionized healthcare, saving millions of soldiers and civilians from lethal bacterial infections.",
    questions: [
      { id: 1, question: "Who discovered penicillin?", options: ["Louis Pasteur", "Alexander Fleming", "Robert Koch"], correct: "Alexander Fleming", hint: "Check the second sentence." },
      { id: 2, question: "What type of organism was penicillin derived from?", options: ["A virus", "A green mold", "A plant root"], correct: "A green mold", hint: "Check the third sentence." },
      { id: 3, question: "In what year was penicillin discovered?", options: ["1928", "1940", "1859"], correct: "1928", hint: "Check the second sentence." },
      { id: 4, question: "What was Alexander Fleming's nationality and profession?", options: ["French chemist", "Scottish bacteriologist", "German physician"], correct: "Scottish bacteriologist", hint: "Check the second sentence." },
      { id: 5, question: "What type of bacteria was in the contaminated petri dish?", options: ["E. coli", "Staphylococcus", "Streptococcus"], correct: "Staphylococcus", hint: "Check the third sentence." },
      { id: 6, question: "Why did the mold contaminate the petri dish?", options: ["Fleming added it intentionally", "The petri dish was left uncovered", "It grew from the agar substrate"], correct: "The petri dish was left uncovered", hint: "Check the third sentence." },
      { id: 7, question: "What did Fleming observe under the microscope regarding the bacteria?", options: ["The bacteria were eating the mold", "Bacteria immediately surrounding the mold had been destroyed", "The bacteria were completely unaffected"], correct: "Bacteria immediately surrounding the mold had been destroyed", hint: "Check the fourth sentence." },
      { id: 8, question: "What is the scientific name of the green mold?", options: ["Staphylococcus aureus", "Penicillium notatum", "Saccharomyces cerevisiae"], correct: "Penicillium notatum", hint: "Check the fifth sentence." },
      { id: 9, question: "Which two scientists successfully developed penicillin into a mass-produced medicine in the 1940s?", options: ["Watson and Crick", "Howard Florey and Ernst Chain", "Pasteur and Lister"], correct: "Howard Florey and Ernst Chain", hint: "Check the eighth sentence." },
      { id: 10, question: "What type of infections did penicillin save millions of lives from?", options: ["Viral infections", "Bacterial infections", "Fungal infections"], correct: "Bacterial infections", hint: "Check the final sentence." }
    ]
  },
  {
    title: "Renewable Energy Sources",
    text: "Renewable energy is defined as energy generated from natural, self-replenishing resources that do not deplete over time. Unlike fossil fuels such as coal, oil, and natural gas, which take millions of years to form and are finite, renewable resources are virtually inexhaustible. The most common types of renewable energy are solar, wind, and hydroelectric power. Solar energy captures light and heat from the sun using photovoltaic panels to generate clean electricity. Wind energy utilizes massive wind turbines to capture the kinetic energy of moving air and convert it into electrical power. Hydroelectric energy relies on the force of flowing water, usually through a dam, to spin generators. Geothermal energy harnesses heat from deep inside the Earth, while biomass uses organic matter like plants. A major advantage of renewable energy is that it produces little to no greenhouse gases during operation, making it essential for combating global climate change and reducing air pollution.",
    questions: [
      { id: 1, question: "What defines renewable energy?", options: ["Energy from coal", "Energy generated from natural, self-replenishing resources that do not deplete", "Energy that runs out fast"], correct: "Energy generated from natural, self-replenishing resources that do not deplete", hint: "Check the first sentence." },
      { id: 2, question: "Which of these is a renewable energy source?", options: ["Natural gas", "Solar, wind, and hydroelectric energy", "Coal"], correct: "Solar, wind, and hydroelectric energy", hint: "Check the third sentence." },
      { id: 3, question: "Why are fossil fuels considered finite?", options: ["They replenish in a few days", "They take millions of years to form and do not self-replenish quickly", "They are made of water"], correct: "They take millions of years to form and do not self-replenish quickly", hint: "Check the second sentence." },
      { id: 4, question: "What technology captures light and heat from the sun?", options: ["Wind turbines", "Photovoltaic panels", "Steam dams"], correct: "Photovoltaic panels", hint: "Check the fourth sentence." },
      { id: 5, question: "What type of energy do wind turbines capture from moving air?", options: ["Kinetic energy", "Chemical energy", "Thermal energy"], correct: "Kinetic energy", hint: "Check the fifth sentence." },
      { id: 6, question: "What physical force does hydroelectric energy rely on to spin generators?", options: ["Force of blowing wind", "Force of flowing water", "Heat from the Earth"], correct: "Force of flowing water", hint: "Check the sixth sentence." },
      { id: 7, question: "Where does geothermal energy harness heat from?", options: ["Deep inside the Earth", "The Sun's radiation", "Burning wood"], correct: "Deep inside the Earth", hint: "Check the seventh sentence." },
      { id: 8, question: "What materials are used to generate biomass energy?", options: ["Uranium blocks", "Organic matter like plants", "Petroleum liquids"], correct: "Organic matter like plants", hint: "Check the seventh sentence." },
      { id: 9, question: "What is a major advantage of renewable energy during operation?", options: ["It is completely free to build", "It produces little to no greenhouse gases", "It works perfectly without any infrastructure"], correct: "It produces little to no greenhouse gases", hint: "Check the final sentence." },
      { id: 10, question: "What global environmental issue is renewable energy key in combating?", options: ["Global climate change", "Acid rain only", "Soil erosion"], correct: "Global climate change", hint: "Check the final sentence." }
    ]
  },
  {
    title: "Migration Patterns of Birds",
    text: "Bird migration is one of the most spectacular natural phenomena, involving the seasonal movement of billions of birds across the globe. Many bird species migrate twice a year, traveling thousands of miles between their breeding grounds and their wintering habitats. The primary drivers of migration are food availability and the need for safe nesting sites to raise their young. Navigating these immense distances requires incredible precision. Birds utilize a combination of sophisticated navigational tools, including the Earth's magnetic field, the position of the sun during the day, and the patterns of stars at night. They also rely on geographical landmarks such as coastlines, rivers, and mountain ranges to guide their path. This long-distance journey is fraught with severe risks, including harsh weather, predators, exhaustion, and human-made obstacles like wind turbines and bright city lights. Despite the dangers, migration is a successful evolutionary strategy that ensures species survival by maximizing resource access.",
    questions: [
      { id: 1, question: "Why do birds migrate?", options: ["To escape predators only", "To find food and suitable nesting sites to raise young", "To exercise"], correct: "To find food and suitable nesting sites to raise young", hint: "Check the third sentence." },
      { id: 2, question: "What is one tool birds use to navigate?", options: ["Stars, Earth's magnetic field, and the sun", "Man-made compasses", "Radio towers"], correct: "Stars, Earth's magnetic field, and the sun", hint: "Check the fifth sentence." },
      { id: 3, question: "How often do migratory birds travel per year?", options: ["Once a year", "Twice a year", "Every month"], correct: "Twice a year", hint: "Check the second sentence." },
      { id: 4, question: "What are the two geographical endpoints of bird migration?", options: ["Tropical forests and deserts", "Breeding grounds and wintering habitats", "Cities and oceans"], correct: "Breeding grounds and wintering habitats", hint: "Check the second sentence." },
      { id: 5, question: "What makes bird navigation highly precise?", options: ["They follow human planes", "They use sophisticated tools like the Earth's magnetic field and stars", "They memorize the entire map at birth"], correct: "They use sophisticated tools like the Earth's magnetic field and stars", hint: "Check the fifth sentence." },
      { id: 6, question: "When do birds use stellar patterns to guide their journey?", options: ["During the day", "At night", "Only in the winter"], correct: "At night", hint: "Check the fifth sentence." },
      { id: 7, question: "Which of the following is NOT a geographical landmark used by birds?", options: ["Rivers", "Mountain ranges", "Subway tunnels"], correct: "Subway tunnels", hint: "Look at the landmarks listed in the sixth sentence." },
      { id: 8, question: "What are some natural risks of bird migration?", options: ["Harsh weather and predators", "Industrial pollutants and plastic", "Lack of wings"], correct: "Harsh weather and predators", hint: "Check the seventh sentence." },
      { id: 9, question: "What human-made obstacles are dangerous to migrating birds?", options: ["Highways and bridges", "Wind turbines and bright city lights", "Boats and ships"], correct: "Wind turbines and bright city lights", hint: "Check the seventh sentence." },
      { id: 10, question: "Why is migration considered a successful evolutionary strategy?", options: ["It ensures species survival by maximizing resource access", "It makes birds fly faster", "It reduces their lifespan"], correct: "It ensures species survival by maximizing resource access", hint: "Check the final sentence." }
    ]
  },
  {
    title: "Roman Aqueducts",
    text: "The ancient Romans were masters of civil engineering, and their magnificent aqueducts are testament to their technical sophistication. Aqueducts were long, elevated stone channels designed to transport clean, fresh water from distant mountain springs directly into bustling cities and towns. Because they lacked mechanical pumps, Roman engineers had to rely entirely on gravity. They designed the aqueducts with a very slight and consistent downward slope, allowing water to flow smoothly over distances of dozens of miles. When encountering deep valleys, engineers constructed grand multi-tiered stone arch bridges to support the elevated water channels. Once the water arrived in a city, it flowed into large distribution tanks. This reliable and abundant water supply revolutionized urban life, fueling public baths, large decorative fountains, public latrines, and the private homes of wealthy citizens. It significantly improved public sanitation and health. Many Roman aqueducts were so exceptionally built that parts of them still stand today, over two thousand years later.",
    questions: [
      { id: 1, question: "What was the purpose of Roman aqueducts?", options: ["To transport armies", "To transport clean, fresh water from mountain springs", "To act as defensive walls"], correct: "To transport clean, fresh water from mountain springs", hint: "Check the second sentence." },
      { id: 2, question: "What force kept the water flowing in the aqueducts?", options: ["Steam engines", "Gravity", "Animal power"], correct: "Gravity", hint: "Check the third sentence." },
      { id: 3, question: "Why did the aqueducts rely entirely on gravity?", options: ["Because water was very light", "Because they lacked mechanical pumps", "Because gravity was stronger back then"], correct: "Because they lacked mechanical pumps", hint: "Check the third sentence." },
      { id: 4, question: "What slope design allowed water to flow smoothly?", options: ["A steep vertical drop", "A very slight and consistent downward slope", "A flat horizontal level"], correct: "A very slight and consistent downward slope", hint: "Check the fourth sentence." },
      { id: 5, question: "Over what scale of distance could the water travel using this slope?", options: ["A few hundred feet", "Dozens of miles", "Across entire oceans"], correct: "Dozens of miles", hint: "Check the fourth sentence." },
      { id: 6, question: "What architectural feature was built to support channels over deep valleys?", options: ["Suspension cables", "Grand multi-tiered stone arch bridges", "Wooden dams"], correct: "Grand multi-tiered stone arch bridges", hint: "Check the fifth sentence." },
      { id: 7, question: "Where was water held when it first arrived in a Roman city?", options: ["In individual buckets", "In large distribution tanks", "In a central lake"], correct: "In large distribution tanks", hint: "Check the sixth sentence." },
      { id: 8, question: "Whose private homes received water from these aqueducts?", options: ["All citizens equally", "Wealthy citizens", "Only the Roman Emperor"], correct: "Wealthy citizens", hint: "Check the seventh sentence." },
      { id: 9, question: "How did aqueducts impact urban public health?", options: ["By supplying clean water that improved sanitation", "By causing flooding in slums", "By making cities dusty"], correct: "By supplying clean water that improved sanitation", hint: "Check the eighth sentence." },
      { id: 10, question: "How long have some of these structures survived?", options: ["Over 200 years", "Over 2,000 years", "Less than a century"], correct: "Over 2,000 years", hint: "Check the final sentence of the passage." }
    ]
  },
  {
    title: "Tundra Ecosystem",
    text: "The tundra is a vast, barren biome characterized by its extreme cold, low temperatures, and lack of trees. Located in the high latitudes of the Northern Hemisphere, primarily surrounding the Arctic Circle, the tundra experiences incredibly harsh winters and brief, cool summers. A defining feature of the tundra is its soil condition. Just below the thin topsoil layer, the ground remains permanently frozen year-round, a phenomenon known as permafrost. This solid frozen layer prevents deep root systems from developing, which is the primary reason why trees cannot grow in this biome. Additionally, permafrost blocks rainwater from draining deep into the earth, creating shallow bogs and ponds during the summer melt. The vegetation in the tundra is limited to low-growing, highly resilient species such as mosses, lichens, grasses, and small shrubs. These plants are adapted to survive strong winds, low sunlight, and dry conditions. Animal species like caribou, arctic foxes, and snowy owls have also evolved thick fur or feathers to survive the freezing tundra climate.",
    questions: [
      { id: 1, question: "What is permafrost?", options: ["Frozen rain", "Permanently frozen ground just below the thin topsoil layer", "Snow that never melts"], correct: "Permanently frozen ground just below the thin topsoil layer", hint: "Check the third and fourth sentences." },
      { id: 2, question: "What type of plants grow in the tundra?", options: ["Tall pine trees", "Mosses, lichens, grasses, and small shrubs", "Fruit trees"], correct: "Mosses, lichens, grasses, and small shrubs", hint: "Check the seventh sentence." },
      { id: 3, question: "Where is the tundra biome geographically located?", options: ["In the Southern Hemisphere near the equator", "In high latitudes of the Northern Hemisphere surrounding the Arctic Circle", "Near sea-level islands"], correct: "In high latitudes of the Northern Hemisphere surrounding the Arctic Circle", hint: "Check the second sentence." },
      { id: 4, question: "What are winters and summers like in the tundra?", options: ["Extremely hot and wet", "Harsh winters and brief, cool summers", "Mild winters and very hot summers"], correct: "Harsh winters and brief, cool summers", hint: "Check the second sentence." },
      { id: 5, question: "Why does permafrost prevent trees from growing in the tundra?", options: ["It is too dark", "It prevents deep root systems from developing", "It lacks any nutrients"], correct: "It prevents deep root systems from developing", hint: "Check the fifth sentence." },
      { id: 6, question: "What surface water features are created by permafrost during the summer melt?", options: ["Shallow bogs and ponds", "Deep underground rivers", "Dry sand dunes"], correct: "Shallow bogs and ponds", hint: "Check the sixth sentence." },
      { id: 7, question: "How tall are tundra plants typically?", options: ["Extremely tall", "Low-growing", "Medium height"], correct: "Low-growing", hint: "Check the seventh sentence." },
      { id: 8, question: "What environmental conditions must tundra plants adapt to survive?", options: ["Acidic soil and floods", "Strong winds, low sunlight, and dry conditions", "Insects and shade"], correct: "Strong winds, low sunlight, and dry conditions", hint: "Check the eighth sentence." },
      { id: 9, question: "Name three animal species mentioned that live in the tundra.", options: ["Lions, tigers, and bears", "Caribou, arctic foxes, and snowy owls", "Camels, lizards, and tortoises"], correct: "Caribou, arctic foxes, and snowy owls", hint: "Check the final sentence." },
      { id: 10, question: "What physical adaptations do tundra animals have to survive freezing temperatures?", options: ["Large wings", "Thick fur or feathers", "Sharp claws"], correct: "Thick fur or feathers", hint: "Check the final sentence." }
    ]
  },
  {
    title: "Sound Waves and Hearing",
    text: "Sound is a form of energy that travels in waves, enabling us to communicate, enjoy music, and stay aware of our environment. Sound is created when an object vibrates, such as a guitar string or human vocal cords. This mechanical vibration pushes against nearby air molecules, creating a chain reaction of pressure waves known as longitudinal sound waves. Sound waves require a physical medium—such as air, water, or solid wood—to travel, meaning sound cannot exist in the vacuum of space. When these traveling waves enter our ear canal, they strike a thin membrane called the eardrum, causing it to vibrate. These vibrations are then amplified by three tiny bones in the middle ear before reaching the cochlea, a fluid-filled structure in the inner ear. Inside the cochlea, microscopic hair cells convert the physical vibrations into electrical signals. Finally, these signals travel through the auditory nerve to the brain, which interprets them as recognizable sounds.",
    questions: [
      { id: 1, question: "How is sound created?", options: ["By light reflection", "When an object vibrates", "By chemical reactions"], correct: "When an object vibrates", hint: "Check the second sentence." },
      { id: 2, question: "What part of the ear vibrates first when hit by sound waves?", options: ["The brain", "The eardrum", "The inner canal"], correct: "The eardrum", hint: "Check the fifth sentence." },
      { id: 3, question: "What form of energy is sound?", options: ["Thermal energy", "Energy that travels in waves", "Magnetic force"], correct: "Energy that travels in waves", hint: "Check the first sentence." },
      { id: 4, question: "What are two examples of vibrating structures mentioned?", options: ["Piano keys and wind", "Guitar strings or human vocal cords", "Drums and speakers"], correct: "Guitar strings or human vocal cords", hint: "Check the second sentence." },
      { id: 5, question: "What is the scientific name for the pressure waves that make up sound?", options: ["Transverse electromagnetic waves", "Longitudinal sound waves", "Gravitational waves"], correct: "Longitudinal sound waves", hint: "Check the third sentence." },
      { id: 6, question: "Why can sound NOT travel in the vacuum of outer space?", options: ["Because it is too cold", "Because sound waves require a physical medium to travel", "Because gravity is too low"], correct: "Because sound waves require a physical medium to travel", hint: "Check the fourth sentence." },
      { id: 7, question: "What mediums are mentioned that sound can travel through?", options: ["Only air", "Air, water, or solid wood", "Only metals"], correct: "Air, water, or solid wood", hint: "Check the fourth sentence." },
      { id: 8, question: "What is the role of the three tiny bones in the middle ear?", options: ["To filter noise", "To amplify vibrations", "To protect the inner ear"], correct: "To amplify vibrations", hint: "Check the sixth sentence." },
      { id: 9, question: "Where are microscopic hair cells located that convert physical vibrations into electrical signals?", options: ["In the eardrum", "In the cochlea", "In the ear canal"], correct: "In the cochlea", hint: "Check the seventh and eighth sentences." },
      { id: 10, question: "What nerve carries the electrical signals from the ear to the brain?", options: ["Optic nerve", "Auditory nerve", "Sciatic nerve"], correct: "Auditory nerve", hint: "Check the final sentence." }
    ]
  },
  {
    title: "The Invention of the Printing Press",
    text: "The invention of the printing press is widely regarded as one of the most critical events of the second millennium, fundamentally reshaping human civilization. In the 1440s, a German goldsmith named Johannes Gutenberg developed the movable-type printing press in Mainz, Germany. Gutenberg's genius lay in combining several existing technologies: movable metal type, oil-based ink, and a wooden screw press adapted from agricultural wine presses. Before this invention, books had to be copied by hand, a laborious process that took months or years, making books extremely rare and expensive items owned only by the wealthy or the Church. Gutenberg's machine allowed pages of text to be assembled quickly using reusable metal letters and printed in rapid succession. This dramatically lowered the cost of producing books and made them widely accessible to the general public. As a result, literacy rates skyrocketed across Europe, universities flourished, and scientific, religious, and political ideas spread with unprecedented speed, fueling the Renaissance and the Scientific Revolution.",
    questions: [
      { id: 1, question: "Who invented the movable-type printing press?", options: ["William Shakespeare", "Johannes Gutenberg", "Leonardo da Vinci"], correct: "Johannes Gutenberg", hint: "Check the second sentence." },
      { id: 2, question: "What was a major result of the printing press?", options: ["Fewer books were written", "Dramatically increased literacy rates and accelerated spread of knowledge", "Worse education"], correct: "Dramatically increased literacy rates and accelerated spread of knowledge", hint: "Check the final sentence." },
      { id: 3, question: "When and where was the printing press developed?", options: ["In the 1440s in Mainz, Germany", "In 105 AD in China", "In the 17th century in England"], correct: "In the 1440s in Mainz, Germany", hint: "Check the second sentence." },
      { id: 4, question: "What was Johannes Gutenberg's profession?", options: ["Scholar", "Goldsmith", "Priest"], correct: "Goldsmith", hint: "Check the second sentence." },
      { id: 5, question: "What agricultural tool was adapted to make the printing press?", options: ["A plow", "A wine screw press", "A grain thresher"], correct: "A wine screw press", hint: "Check the third sentence." },
      { id: 6, question: "How were books made before the printing press?", options: ["They were printed on wood blocks", "They had to be copied by hand", "They were spoken aloud only"], correct: "They had to be copied by hand", hint: "Check the fourth sentence." },
      { id: 7, question: "Who primarily owned books before Gutenberg's invention?", options: ["Every peasant family", "The wealthy or the Church", "Only kings"], correct: "The wealthy or the Church", hint: "Check the fourth sentence." },
      { id: 8, question: "What did Gutenberg use to assemble pages of text quickly?", options: ["Clay carvings", "Reusable metal letters (movable metal type)", "Handwritten sheets"], correct: "Reusable metal letters (movable metal type)", hint: "Check the fifth sentence." },
      { id: 9, question: "How did the printing press affect the price and availability of books?", options: ["It made them rare and more expensive", "It dramatically lowered the cost and made them widely accessible", "It had no effect on pricing"], correct: "It dramatically lowered the cost and made them widely accessible", hint: "Check the sixth sentence." },
      { id: 10, question: "What two major historical movements were fueled by the spread of ideas from the press?", options: ["The Industrial Revolution and the Middle Ages", "The Renaissance and the Scientific Revolution", "The Crusades and the Roman Empire"], correct: "The Renaissance and the Scientific Revolution", hint: "Check the final sentence." }
    ]
  },
  {
    title: "How Fossils Form",
    text: "Fossils are the invaluable remains, traces, or impressions of ancient organisms that lived millions of years ago, offering scientists a window into prehistoric life on Earth. The process of fossilization is extremely rare, as most dead organisms decay completely without leaving a trace. For a fossil to form, specific environmental conditions must be met. First, when an animal or plant dies, its remains must be quickly buried under layers of sediment, such as mud, sand, or silt. This rapid burial is crucial because it protects the remains from scavengers and shields them from oxygen, which slows down decay. Over millions of years, more sediment piles on top, compressing the lower layers into solid sedimentary rock. Meanwhile, mineral-rich groundwater slowly seeps through the buried bones or shells. Through a process called permineralization, these minerals replace the organic matter cell by cell, eventually turning the remains into solid stone. Fossils are finally revealed millions of years later through the natural erosion of rock layers.",
    questions: [
      { id: 1, question: "How do fossils form?", options: ["Organisms freeze in ice immediately", "Organisms are quickly buried by sediment and replaced by minerals over millions of years", "Organisms are dried by the sun"], correct: "Organisms are quickly buried by sediment and replaced by minerals over millions of years", hint: "Check the fourth and eighth sentences." },
      { id: 2, question: "What materials bury the organism to start fossilization?", options: ["Lava", "Sediment like mud, sand, or silt", "Ice sheets"], correct: "Sediment like mud, sand, or silt", hint: "Check the fourth sentence." },
      { id: 3, question: "Why is fossilization considered extremely rare?", options: ["Because ancient animals were very small", "Because most dead organisms decay completely without leaving a trace", "Because rocks do not last long"], correct: "Because most dead organisms decay completely without leaving a trace", hint: "Check the second sentence." },
      { id: 4, question: "What does rapid burial protect the remains from?", options: ["Underground heat", "Scavengers and oxygen", "Rainwater"], correct: "Scavengers and oxygen", hint: "Check the fifth sentence." },
      { id: 5, question: "Why is shielding remains from oxygen important during fossilization?", options: ["It keeps them warm", "It slows down decay", "It turns them blue"], correct: "It slows down decay", hint: "Check the fifth sentence." },
      { id: 6, question: "What happens to sediment layers over millions of years?", options: ["They evaporate", "They compress into solid sedimentary rock", "They remain loose sand"], correct: "They compress into solid sedimentary rock", hint: "Check the sixth sentence." },
      { id: 7, question: "What type of water seeps through buried bones or shells?", options: ["Pure rainwater", "Mineral-rich groundwater", "Saltwater from the ocean surface"], correct: "Mineral-rich groundwater", hint: "Check the seventh sentence." },
      { id: 8, question: "What is the scientific name for the cell-by-cell mineral replacement process?", options: ["Photosynthesis", "Permineralization", "Erosion"], correct: "Permineralization", hint: "Check the eighth sentence." },
      { id: 9, question: "What is organic matter eventually turned into during permineralization?", options: ["Coal dust", "Solid stone", "Fossil fuel liquids"], correct: "Solid stone", hint: "Check the eighth sentence." },
      { id: 10, question: "How are fossils finally revealed and discovered after millions of years?", options: ["By digging up every piece of soil on Earth", "Through the natural erosion of rock layers", "By volcanic eruptions blowing them up"], correct: "Through the natural erosion of rock layers", hint: "Check the final sentence of the passage." }
    ]
  },
  {
    title: "Ocean Currents",
    text: "Ocean currents are continuous, predictable, and directed movements of seawater that flow through the world's oceans. These vast marine rivers are generated by a complex interplay of physical forces, including global wind patterns, differences in water temperature and salinity (which affect density), and the rotation of the Earth, a force known as the Coriolis effect. Ocean currents are divided into two main types: surface currents, which are driven primarily by wind, and deep-ocean currents, which are driven by density differences in a process called thermohaline circulation. Together, these currents act as a giant global conveyor belt. They play a critical role in regulating the Earth's climate by transporting warm water and heat from the equator toward the freezing polar regions, and sending cold water back toward the tropics. Without this continuous heat distribution system, equatorial regions would be extremely hot, while polar regions would be far colder, making much of the planet uninhabitable.",
    questions: [
      { id: 1, question: "What generates ocean currents?", options: ["Underwater earthquakes only", "Global wind, temperature/salinity differences, and the Earth's rotation", "Ship traffic"], correct: "Global wind, temperature/salinity differences, and the Earth's rotation", hint: "Check the second sentence." },
      { id: 2, question: "How do ocean currents affect global climate?", options: ["By cooling the sun", "By transporting warm water from the equator toward polar regions and cold water back", "By creating new islands"], correct: "By transporting warm water from the equator toward polar regions and cold water back", hint: "Check the sixth sentence." },
      { id: 3, question: "What are ocean currents compared to in the text?", options: ["Deep ocean trenches", "Vast marine rivers / global conveyor belt", "Tidal waves"], correct: "Vast marine rivers / global conveyor belt", hint: "Check the second and fifth sentences." },
      { id: 4, question: "What force is caused by the rotation of the Earth?", options: ["Gravitational force", "Coriolis effect", "Magnetic field"], correct: "Coriolis effect", hint: "Check the second sentence." },
      { id: 5, question: "What two properties of water affect its density?", options: ["Volume and pressure", "Temperature and salinity", "Color and clarity"], correct: "Temperature and salinity", hint: "Check the second sentence." },
      { id: 6, question: "Into how many main types are ocean currents divided?", options: ["Two main types", "Four main types", "Hundreds of types"], correct: "Two main types", hint: "Check the third sentence." },
      { id: 7, question: "What force primarily drives surface currents?", options: ["Heat from the seabed", "Wind patterns", "Earthquakes"], correct: "Wind patterns", hint: "Check the third sentence." },
      { id: 8, question: "What is the density-driven process for deep-ocean currents called?", options: ["Coriolis circulation", "Thermohaline circulation", "Atmospheric pressure"], correct: "Thermohaline circulation", hint: "Check the third sentence." },
      { id: 9, question: "Where is heat transported from by the global conveyor belt?", options: ["From polar regions to the equator", "From the equator toward the freezing polar regions", "From deep trenches to the surface"], correct: "From the equator toward the freezing polar regions", hint: "Check the sixth sentence." },
      { id: 10, question: "What would happen to the equator and poles without ocean currents?", options: ["The equator would be extremely hot and the poles far colder, making the planet uninhabitable", "The poles would melt completely and the equator freeze", "Nothing would change"], correct: "The equator would be extremely hot and the poles far colder, making the planet uninhabitable", hint: "Check the final sentence of the text." }
    ]
  }
];
