import * as fs from 'fs';

// High quality academic, scientific, environmental, historical, psychological, economic, and technological passages for Module 2

const EASY_PASSAGES_POOL = [
  "The natural {en:vironment:Surroundings or conditions in which living organisms reside.} is vital for global biodiversity. Conserving native {ha:bitats:Natural homes of animals or plants.} ensures the survival of endangered species. Pollution severely damages {aq:uatic:Relating to water ecosystems.} ecosystems and reduces freshwater quality. Sustainable farming practices protect soil {fe:rtility:Ability of soil to sustain agricultural plant growth.} and reduce chemical runoff. Every community must participate in environmental {pr:eservation:Act of keeping something safe and undamaged.}.",
  "Solar energy is an efficient {re:newable:Source of energy that is not depleted when used.} resource that reduces greenhouse gas emissions. Photovoltaic panels convert sunlight directly into electrical {po:wer:Energy used to operate machines or appliances.}. Modern cities are installing clean energy infrastructure to achieve carbon {ne:utrality:State of releasing no net greenhouse gases.}. Reducing fossil fuel dependency improves overall air {qu:ality:Standard or condition of something.}. Energy conservation is essential for future generations.",
  "Forest ecosystems act as vital carbon {si:nks:Natural reservoirs that absorb carbon dioxide.} that absorb greenhouse gases from the atmosphere. Reforestation projects restore damaged woodlands and support wild {po:pulations:Groups of organisms of the same species.}. Illegal logging destroys ancient trees and threatens rare fauna. Protecting forests helps stabilize the global climate {sy:stem:Complex whole composed of connected parts.}. Communities benefit from cleaner air and healthy water cycles.",
  "Marine life relies on healthy coral reefs for shelter and {nu:trition:Substances required for health and growth.}. Rising ocean temperatures cause severe coral {bl:eaching:Loss of color and vital algae in corals.}. Marine protected areas prevent destructive commercial fishing practices. Preserving coastal ecosystems protects shorelines from severe storm {su:rges:Sudden powerful forward movements of water.}. Marine conservation is critical for planetary health.",
  "Freshwater rivers supply drinking water and irrigate agricultural {cr:ops:Cultivated plants grown as food.}. Over-extraction of groundwater depletes subterranean aquifers. Efficient irrigation technology reduces agricultural water {wa:stage:Action or process of wasting something.}. Protecting watershed regions maintains steady river flow and water purity. Communities must manage liquid resources responsibly.",
  "Astronomical observatories use powerful {te:lescopes:Instruments designed to make distant objects appear nearer.} to study distant galaxies. Deep space probes collect detailed imagery of planetary {su:rfaces:Outer or topmost boundary of an object.}. Scientists analyze cosmic radiation to understand the origin of the universe. Orbital satellites provide continuous meteorological and global positioning {da:ta:Facts and statistics collected for analysis.}. Space exploration expands human knowledge of the cosmos.",
  "The solar system consists of eight planets orbiting a central {st:ar:Luminous celestial body of plasma.}. Earth is situated in the habitable zone where liquid water can {ex:ist:Have objective reality or live.}. Mars possesses thin atmospheric gases and frozen water at its poles. Robotic rovers examine Martian soil for signs of ancient microbial {li:fe:Condition that distinguishes living organisms.}. Interplanetary missions require advanced propulsion technology.",
  "Lunar missions have provided valuable samples of regolith and rocks. Scientists study lunar craters to determine the history of meteoroid {im:pacts:Collisions of one object against another.}. Permanent lunar bases could serve as stepping stones for deeper interplanetary {jo:urneys:Acts of traveling from one place to another.}. Solar panels on the Moon generate continuous electric power during lunar days. Human spaceflight inspires technological breakthroughs.",
  "Space telescopes stationed beyond Earth atmosphere capture high-resolution {im:ages:Visual representations of things.}. Eliminating atmospheric distortion allows astronomers to detect distant exoplanets. Spectral analysis reveals the chemical composition of exoplanet atmospheres. Searching for biosignatures helps scientists evaluate potential extraterrestrial {ha:bitability:Suitability for living organisms.}. Astrophysics advances our understanding of physics.",
  "Artificial satellites orbit Earth in designated orbital tracks. Telecommunication satellites transmit television, internet, and radio {si:gnals:Gestures, actions, or sounds conveying information.}. Weather satellites monitor hurricane development and atmospheric pressure changes. Space debris poses a collision hazard to active orbital spacecraft. Engineers design orbital cleanup systems to mitigate space clutter.",
  "The human circulatory system transports oxygen and essential {nu:trients:Substances supplying nourishment for growth.} through blood vessels. The heart pumps oxygenated blood through arteries to body tissues. Red blood cells contain hemoglobin, which binds oxygen {mo:lecules:Groups of atoms bonded together.}. Proper physical exercise strengthens cardiovascular muscles and boosts stamina. Maintaining healthy blood pressure reduces the risk of heart disease.",
  "The central nervous system consists of the brain and spinal {co:rd:Long thin structure carrying nerve impulses.}. Neurons transmit electrical signals across synaptic gaps to process information. Sensory organs detect environmental stimuli and convey signals to the cerebral {co:rtex:Outer layer of neural tissue in the brain.}. Regular physical rest and mental stimulation optimize neural cognitive functions. Healthy sleep cycles consolidate memory pathways.",
  "Human digestion breaks down food into simple chemical compounds. The stomach uses gastric acids and enzymes to dissolve dietary {pr:oteins:Complex organic macromolecules essential for life.}. Small intestines absorb vital vitamins, minerals, and glucose into the bloodstream. Dietary fiber promotes beneficial intestinal bacterial flora and smooth digestion. Balanced nutrition prevents metabolic disorders.",
  "The human immune system protects the body against invading pathogenic {mi:crobes:Microscopic organisms causing disease.}. White blood cells produce specialized antibodies to neutralize foreign antigens. Immunization trains the immune system to recognize specific viral strains quickly. Maintaining good personal hygiene minimizes exposure to infectious agents. Adequate hydration and nutrition support immune response.",
  "Respiratory organs facilitate gas exchange between blood and the external atmosphere. Lungs absorb oxygen and eliminate carbon dioxide during cellular {re:spiration:Process of inhaling oxygen and exhaling carbon dioxide.}. Respiratory cilia filter dust particles and pollutants from inhaled air. Clean air environments protect pulmonary tissues from chronic inflammation. Regular exercise expands lung capacity and oxygen intake.",
  "Ancient agricultural civilizations flourished near fertile river valley {re:gions:Extensive geographic areas.}. Farmers constructed irrigation networks to divert river water to cropland. Surplus food production allowed communities to develop urban centers and specialized {tr:ades:Occupations requiring manual or mechanical skill.}. Written scripts emerged to record commercial transactions and legal codes. Agriculture established the foundation of organized societies.",
  "The invention of the printing press transformed European literacy and information {di:ssemination:Act of spreading something widely.}. Bound books became affordable and accessible to wider social classes. Scientific treatises and philosophical ideas spread rapidly across international borders. Standardized print encouraged national language development and educational reform. Mass printing accelerated the intellectual progress of the Enlightenment.",
  "Maritime trade routes connected ancient empires across vast oceanic distances. Merchant vessels transported spices, silk, ceramics, and precious {me:tals:Solid material that is typically hard and shiny.}. Cultural exchange accompanied commercial trade, sharing artistic styles and ideas. Coastal port cities grew into wealthy cosmopolitan centers of international commerce. Maritime navigation required accurate charts and astronomical tracking.",
  "The Industrial Revolution introduced mechanized manufacturing powered by steam {en:gines:Machines with moving parts that convert power into motion.}. Factories replaced traditional handcraft workshops, increasing output speed dramatically. Railroad networks transported raw materials and manufactured goods across continents. Urban populations expanded rapidly as agricultural workers moved toward industrial cities. Technological innovation reshaped economic structures.",
  "Archaeological excavations uncover ancient architectural structures and domestic artifacts. Scholars analyze pottery fragments, tools, and inscriptions to reconstruct historical {cu:ltures:Customs, arts, and social institutions of a group.}. Radiocarbon dating determines the age of organic materials found at historic sites. Preserving heritage monuments protects human historical memory for future scholars. Museum exhibitions educate the public about ancestral traditions."
];

const NORMAL_PASSAGES_POOL = [
  "Urbanization in modern metropolises presents complex spatial challenges for civic planners. Upgrading public {in:frastructure:Basic physical structures needed for operation of society.} reduces traffic congestion and carbon emissions. Integrating rapid transit railways with electric bus networks improves urban accessibility. Green architecture incorporates energy-efficient materials and rooftop vegetation to lower municipal heat island effects. Sustainable city management requires balanced economic investment and environmental stewardship.",
  "Biotechnology and genetic modification have revolutionized contemporary agricultural production. Gene editing techniques like CRISPR enable scientists to introduce drought-resistant traits into crop plants. Enhanced crop resilience increases food security in regions experiencing extreme climate variability. However, regulatory frameworks must carefully evaluate bio-safety risks and potential ecosystem disruptions. Transparent public communication builds societal trust in bio-engineering innovations.",
  "Cognitive psychology investigates the mental mechanisms involved in memory encoding, storage, and retrieval. Short-term working memory processes immediate information with limited capacity, whereas long-term memory organizes vast neural networks over a lifetime. Consolidating new knowledge requires focused attention, emotional relevance, and systematic repetition. Neuroscientists study synaptic plasticity to understand how brain connections strengthen during learning. Healthy sleep hygiene is indispensable for optimal cognitive performance.",
  "Oceanography reveals that deep marine trenches host resilient biological communities adapted to extreme conditions. Organisms at abyssal depths withstand enormous hydrostatic pressure and complete absence of sunlight. Hydrothermal vents emit mineral-rich thermal fluids that nourish specialized chemosynthetic bacteria. These unique micro-organisms form the foundation of rich deep-sea ecosystems independent of solar energy. Protecting marine biodiversity is essential for global ecological balance.",
  "Volcanic eruptions occur when subterranean magma ascends through tectonic fissures due to pressure buildup. Eruptions discharge toxic gases, incandescent ash clouds, and pyroclastic flows into the atmosphere. Despite localized hazards, volcanic ash enriches surrounding soils with essential minerals for agriculture. Furthermore, geothermal energy stations harness underground volcanic heat to generate renewable electricity. Geologists utilize seismic monitoring equipment to forecast volcanic activity accurately.",
  "Artificial intelligence algorithms analyze massive datasets to identify subtle statistical patterns and anomalies. Machine learning models assist healthcare professionals by diagnosing medical conditions from complex radiographic imaging. Autonomous vehicles utilize computer vision and sensor fusion to navigate dynamic urban environments safely. Ethical AI design mandates algorithm transparency, data privacy protection, and continuous human oversight. Responsible technology development prevents systemic bias in automated decision-making.",
  "Microbiology examines microscopic organisms, including beneficial bacteria, fungi, and pathogenic viruses. Microbial communities in the human gut microbiome regulate nutrient digestion, metabolic health, and immune defense. However, antibiotic overuse accelerates the evolutionary emergence of resistant superbug strains. Medical researchers are developing targeted bacteriophage therapies and novel antimicrobial compounds. Maintaining balanced microbial ecosystems is crucial for human health.",
  "The hydrological water cycle continuously redistributes moisture across terrestrial landmasses, oceans, and atmosphere. Solar radiation evaporates surface water from oceans into atmospheric water vapor. As warm vapor rises into cooler altitude layers, condensation forms visible clouds and atmospheric precipitation. Rain and snow replenish subterranean aquifers, lakes, and river systems, sustaining terrestrial life. Climate change alters precipitation patterns, causing unpredictable droughts and flooding.",
  "Quantum mechanics describes the fundamental physical behavior of subatomic particles at microscopic scales. Quantum phenomena such as superposition and entanglement defy classical physics principles. Quantum computing uses subatomic qubits to perform complex computational tasks exponentially faster than binary supercomputers. This emerging technology promises breakthroughs in molecular simulation, material science, and cryptography. Scientific research continues to unlock quantum mechanics applications.",
  "Archival preservation combines chemistry, material science, and museum curation to conserve rare historical manuscripts. Exposure to ultraviolet radiation, humidity fluctuations, and atmospheric pollutants degrades cellulose paper fibers over time. Conservators store delicate historical documents in climate-controlled, acid-free storage chambers. High-resolution digital scanning creates permanent backups, enabling global scholars to study historic documents without damaging physical artifacts."
];

const HARD_PASSAGES_POOL = [
  "The strategic overhaul of global supply chain logistics is essential for maintaining international commercial stability. Port automation and automated freight handling increase throughput capacity at major maritime container terminals. Machine learning algorithms optimize shipping routes, fuel consumption, and cargo distribution in real time. Supply chain vulnerabilities exposed by geopolitical conflicts highlight the necessity of regional manufacturing diversification. Resilient logistics networks mitigate market volatility and inflationary price pressures.",
  "Neuroscientific investigation into neurodegenerative diseases emphasizes the role of misfolded protein accumulation in cerebral tissues. Pathological aggregates such as amyloid plaques and tau tangles disrupt synaptic transmission and trigger chronic neuroinflammation. Advanced molecular imaging and biomarker assays allow early detection of cognitive decline before irreversible structural damage occurs. Therapeutic interventions aim to enhance cellular clearance mechanisms and protect neural integrity. Comprehensive clinical research remains paramount for developing disease-modifying therapies.",
  "Atmospheric chemistry demonstrates that stratospheric ozone depletion stems from anthropogenic emissions of halogenated compounds. Synthetic chlorofluorocarbons release chlorine radicals upon exposure to intense ultraviolet radiation in the upper atmosphere. These reactive chlorine atoms catalytically destroy ozone molecules, exposing the biosphere to harmful ultraviolet rays. The international implementation of the Montreal Protocol successfully curtailed ozone-depleting substances, showcasing global environmental cooperation. Continuous atmospheric monitoring ensures the ongoing recovery of the ozone shield.",
  "Macroeconomic theory analyzes the intricate interrelationships between monetary policy, inflation metrics, and employment levels. Central banks adjust benchmark interest rates to regulate credit availability and stabilize currency purchasing power. Unprecedented supply-side disruptions can trigger stagflationary pressures, complicating fiscal intervention strategies. Quantitative easing programs expand central bank balance sheets to inject liquidity during severe financial downturns. Sustainable economic growth requires balanced fiscal discipline and structural market efficiency.",
  "Ecosystem restoration ecology employs scientific principles to rehabilitate severely degraded natural landscapes. Native species reintroduction restores trophic food web interactions and enhances biological resilience against invasive species. Wetlands restoration mitigates downstream flood risk by acting as natural hydrological sponges and filtering chemical pollutants. Long-term ecological monitoring measures ecosystem recovery metrics like soil carbon sequestration and species richness. Community engagement ensures the enduring success of conservation initiatives.",
  "Quantum electrodynamics formulates the quantum mechanical interaction between light and charged matter with extreme mathematical precision. Perturbation theory and Feynman diagrams allow physicists to calculate electron magnetic moments and atomic spectral line shifts accurately. High-energy particle accelerators test quantum field predictions under extreme energy densities, probing fundamental symmetries. Unifying quantum field theory with general relativity remains a central objective of theoretical physics. Quantum electrodynamics represents a cornerstone of modern physical science.",
  "Epidemiological modeling utilizes stochastic algorithms to forecast infectious disease transmission dynamics across human populations. Key parameters like the basic reproduction number and incubation periods inform public health intervention strategies. Non-pharmaceutical measures, such as social distancing and targeted contact tracing, flatten infection velocity curves. Mathematical simulations evaluate vaccine coverage thresholds required to establish population-level herd immunity. Global epidemiological surveillance prevents catastrophic pandemic outbreaks.",
  "Structural engineering designs high-rise skyscrapers to withstand extreme seismic accelerations and aerodynamic wind loads. Tuned mass dampers installed near building tops counteract wind-induced oscillations through inertial resistance. Reinforced concrete cores and steel outrigger trusses distribute immense gravitational forces evenly onto deep subterranean pile foundations. Advanced finite element modeling simulates structural stress performance under simulated earthquake conditions. Resilient structural engineering ensures urban safety in seismically active zones.",
  "Environmental economics evaluates the market failure caused by unpriced negative externalities like industrial pollution. Carbon pricing mechanisms, such as cap-and-trade systems and carbon taxation, internalize environmental degradation costs into corporate accounting. Economic incentives encourage private investment in clean technologies and energy-efficient industrial processes. Revenue generated from carbon taxes can fund renewable infrastructure and cushion low-income households against transition costs. Market-based environmental policies harmonize economic development with ecological protection.",
  "Paleoclimatology reconstructs ancient terrestrial climate variations using proxy indicators such as polar ice cores, tree ring chronologies, and ocean sediment layers. Isotopic analysis of trapped atmospheric gas bubbles provides continuous records of greenhouse gas concentrations over hundreds of thousands of years. Solar irradiance cycles and Milankovitch orbital variations drive long-term glacial-interglacial cycles. Studying past climate shifts provides crucial baseline data for parameterizing predictive global climate models."
];

const ADVANCED_PASSAGES_POOL = [
  "Epigenetic mechanisms govern gene expression without altering the underlying deoxyribonucleic acid sequence through chemical modifications such as DNA methylation and histone acetylation. Chromatin remodeling complexes dynamically regulate transcriptional accessibility, determining cellular differentiation during embryonic development. Environmental stressors, including dietary deficiencies, chemical toxins, and chronic psychological stress, induce persistent epigenetic alterations that can endure across cellular divisions. Transgenerational epigenetic inheritance suggests that environmental exposures experienced by ancestral generations may modulate phenotypic disease susceptibility in descendant lineages. Unraveling these complex regulatory networks holds transformative potential for targeted therapeutic interventions in oncology and metabolic disorders.",
  "Quantum information processing leverages superposed quantum states and non-local entanglement to execute computational algorithms beyond classical theoretical limits. Quantum algorithms like Shor's prime factorization algorithm threaten current public-key cryptographic paradigms, necessitating the urgent development of post-quantum lattice-based encryption standards. Fault-tolerant quantum computation requires quantum error correction codes, such as surface codes, which embed logical qubits across topological arrays of physical qubits to suppress environmental decoherence. Physical implementations using superconducting transmon circuits or trapped ytterbium ions demand precise microwave pulse control at cryogenic temperatures near absolute zero. Achieving practical quantum supremacy will revolutionize molecular docking simulations and cryptographic security.",
  "Astrophysical nucleosynthesis models explain the cosmic origin of chemical elements through nuclear fusion processes within stellar interiors and energetic astronomical events. Primordial nucleosynthesis during the early Big Bang epoch produced light isotopes, specifically hydrogen, helium, and trace lithium. Main-sequence stars synthesize heavier elements up to iron through stellar core fusion cycles, beyond which further fusion becomes endothermic. Explosive supernova collapse and rapid neutron capture processes occurring during binary neutron star mergers synthesize heavy r-process elements like gold and platinum. High-resolution astronomical spectroscopy verifies theoretical elemental abundances across ancient galactic stellar populations.",
  "Socioeconomic stratification theory analyzes how structural institutional frameworks perpetuate wealth inequality and social mobility barriers across generations. Capital accumulation, differential access to high-quality educational institutions, and persistent occupational segregation reinforce systemic disparities. Bourdieu's concept of cultural capital emphasizes that subtle social habits, educational credentials, and linguistic demeanor serve as covert mechanisms of class reproduction. Intersectional sociological frameworks examine how race, gender, and socioeconomic status interact to compound systemic disadvantage in urban environments. Policy solutions require comprehensive structural reforms, progressive wealth taxation, and universal social safety net protections.",
  "Computational linguistic analysis utilizes transformer-based neural network architectures equipped with multi-head self-attention mechanisms to process natural language syntax and semantics. Large language models map textual tokens into high-dimensional vector embeddings, capturing complex semantic relationships and contextual dependencies across extended discourse. Pre-training on massive multi-lingual text corpora optimizes parameters to predict probability distributions over vocabulary sequences. Fine-tuning via reinforcement learning from human feedback aligns model outputs with human intent, safety guidelines, and factual consistency. Emerging research focuses on parameter-efficient adaptation, interpretability of hidden representations, and reducing hallucination errors in complex reasoning tasks."
];

function convertRawPassageToTemplate(text: string): string {
  if (text.includes('{') && text.includes('}')) {
    return text;
  }
  const COMMON_STOP_WORDS = new Set([
    'about', 'above', 'across', 'after', 'again', 'against', 'almost', 'along', 'already', 'also', 'although', 'always', 'among', 'another', 'answer', 'around', 'because', 'before', 'behind', 'between', 'beyond', 'both', 'bring', 'could', 'course', 'during', 'each', 'early', 'either', 'enough', 'even', 'every', 'first', 'found', 'from', 'great', 'group', 'however', 'inside', 'into', 'itself', 'just', 'large', 'later', 'light', 'like', 'little', 'made', 'make', 'many', 'more', 'most', 'much', 'must', 'never', 'number', 'often', 'other', 'others', 'overall', 'people', 'place', 'point', 'right', 'same', 'second', 'several', 'should', 'since', 'small', 'some', 'still', 'such', 'their', 'them', 'themselves', 'then', 'there', 'these', 'they', 'things', 'think', 'this', 'those', 'though', 'through', 'today', 'together', 'under', 'until', 'upon', 'using', 'very', 'water', 'well', 'where', 'which', 'while', 'white', 'within', 'without', 'would', 'years'
  ]);

  const wordRegex = /\b([a-zA-Z]{5,})\b/g;
  let matches: { word: string; index: number; length: number }[] = [];
  let match;
  
  while ((match = wordRegex.exec(text)) !== null) {
    const word = match[1];
    if (!COMMON_STOP_WORDS.has(word.toLowerCase())) {
      matches.push({ word, index: match.index, length: word.length });
    }
  }

  if (matches.length === 0) return text;
  
  const targetCount = Math.min(12, Math.max(6, Math.floor(matches.length / 2)));
  const step = matches.length / targetCount;
  const selectedIndices = new Set<number>();
  
  for (let i = 0; i < targetCount; i++) {
    const idx = Math.floor(i * step);
    if (idx < matches.length) {
      selectedIndices.add(idx);
    }
  }

  const selectedMatches = matches.filter((_, i) => selectedIndices.has(i));
  
  let result = '';
  let lastIdx = 0;
  
  for (const item of selectedMatches) {
    result += text.substring(lastIdx, item.index);
    const word = item.word;
    const splitPoint = Math.min(2, Math.floor(word.length / 2));
    const prefix = word.substring(0, splitPoint);
    const missing = word.substring(splitPoint);
    const hint = `Complete the academic word starting with '${prefix}'`;
    result += `{${prefix}:${missing}:${hint}}`;
    lastIdx = item.index + word.length;
  }
  result += text.substring(lastIdx);
  return result;
}

function generateDataset(pool: string[], count: number, levelName: string): string[] {
  const dataset: string[] = [];
  let index = 0;
  
  while (dataset.length < count) {
    const rawPassage = pool[index % pool.length];
    const templated = convertRawPassageToTemplate(rawPassage);
    dataset.push(templated);
    index++;
  }

  return dataset;
}

const easy200 = generateDataset(EASY_PASSAGES_POOL, 200, "Easy");
const normal200 = generateDataset(NORMAL_PASSAGES_POOL, 200, "Normal");
const hard200 = generateDataset(HARD_PASSAGES_POOL, 200, "Hard");
const advanced200 = generateDataset(ADVANCED_PASSAGES_POOL, 200, "Advanced");

fs.writeFileSync('./src/easy_templates_m2_flat.ts', `export const EASY_TEMPLATES_M2_200: string[] = ${JSON.stringify(easy200, null, 2)};\n`);
fs.writeFileSync('./src/normal_templates_m2_flat.ts', `export const NORMAL_TEMPLATES_M2_200: string[] = ${JSON.stringify(normal200, null, 2)};\n`);
fs.writeFileSync('./src/hard_templates_m2_flat.ts', `export const HARD_TEMPLATES_M2_200: string[] = ${JSON.stringify(hard200, null, 2)};\n`);
fs.writeFileSync('./src/advanced_templates_m2_flat.ts', `export const ADVANCED_TEMPLATES_M2_200: string[] = ${JSON.stringify(advanced200, null, 2)};\n`);

console.log('Successfully generated all 4 Module 2 template files!');
